r"""
Exact-rational verification that alpha = 1/6 is the threshold for non-triviality of the
"two-sided" zero-density statement -- the question posed by the author: for zeros
rho = beta + i*gamma of zeta with 0 < gamma, what is the largest alpha such that a POSITIVE
proportion of zeros (asymptotically, as T, h -> infinity with h/T bounded away from 0) satisfy
beta in [alpha, 1-alpha]?

LEAN STATUS.  No hypothesis-class field is certified here; `alpha < 1/6` is the paper's own
hypothesis (Corollary \ref{cor:simpmain}, Corollary 1) and Lean proves the statements outright --
`PositiveProportion.positiveProportion_of_lt_sixth` and `positiveProportion_littlewood_half`
assume nothing beyond `0 < alpha < 1/6`, with `r = 1/2` supplied rather than assumed.  What this
script adds is the exact-rational answer to *why* 1/6 and not more: it is the minimum of A1 over
all chords, attained at r = 1/2, and it is attained exactly.

BACKGROUND
----------
`LittlewoodShort.littlewoodshort` (ZerosInShortIntervals/Littlewood/LittlewoodShort.lean) gives, for
T > 10^12, h < T, r > alpha, and k with sigma_k <= 1-r < sigma_{k+1}:

    N(T-h,T+h,alpha) < (2*A1*h + 2*A4)/pi * log T + (2*A2*h+2*A5)*loglog T + 2*A3*h + A6
                          + O^*((4h+2)/(T-h))

where A1 = A_{1,alpha,r} = (mCoeff(k)*(1-r) + bCoeff(k)) / (2*(r-alpha)).  The coefficient of
`h*log(T)` is therefore `2*A1/pi`.

`Nrect(T1,T2,alpha)` counts zeros with `Re rho > 1-alpha` (one edge).  By the functional equation
(rho zero => 1-rho zero) composed with complex conjugation (rho zero => conj(rho) zero), the map
`rho |-> 1 - conj(rho)` is an EXACT bijection between {zeros with Re > 1-alpha} and {zeros with
Re < alpha} that preserves Im(rho).  So the total count of zeros within alpha of EITHER edge, in
the same height range, is exactly `2*Nrect(T1,T2,alpha)`.

The total zero count N(t+h)-N(t-h) has h*log(t)-coefficient `1/pi` (Riemann-von Mangoldt).  So the
two-sided proportion of zeros OUTSIDE [alpha,1-alpha] has, as T,h -> infinity (h growing with T),
leading coefficient ratio

    2 * (2*A1/pi) / (1/pi)  =  4*A1(alpha,r,k)

and the proportion INSIDE [1-sigma,sigma] = [alpha,1-alpha] tends to `1 - 4*A1(alpha,r,k)`,
minimized appropriately over r (and, via the analogous B1 from the Jensen mechanism,
`RectangularBounds.rectangularjensen`/`B1`, taking whichever of the two mechanisms is smaller).

This script verifies, in EXACT rational arithmetic (no floating point, no arb -- none is needed,
since `sigma(k)`, `vCoeff(k)`, `mCoeff(k)`, `bCoeff(k)` are all rational numbers for every integer
k), that:

  (1) min_r A1(1/6, r) = 1/4 EXACTLY, achieved at r = 1/2 = sigma(0) -- a chord breakpoint;
  (2) hence min(4*A1) = 1 exactly at alpha = 1/6, i.e. the two-sided proportion is exactly 0 in the
      T,h -> infinity limit;
  (3) for alpha strictly less than 1/6 the same r=1/2 gives 4*A1 < 1, a positive two-sided
      proportion (Step 4 exhibits alpha = 1/6 - 1/6000).  For alpha strictly greater than 1/6
      nothing further needs computing: `A1_breakpoint(alpha,k) = vCoeff(k)/(2*(1-sigma(k)-alpha))`
      is increasing in alpha at every k, so the exact k-sweep of Step 2 at alpha = 1/6 already
      shows 4*A1 > 1 for every chord in the swept range k in [-60,2] and every alpha > 1/6; the
      omitted tail k -> -infinity is handled by the monotone-tail bound of Step 3.

THE KEY STRUCTURAL FACT: A1(alpha, r, k) is a MOEBIUS (linear/linear) function of r within each
chord k's domain, since m_k, b_k are constants there; its derivative w.r.t. r has CONSTANT SIGN
(no interior critical point), so on each chord the extremum occurs at an endpoint -- i.e. the
global minimum over all r is attained at one of the countably many chord *breakpoints*
r = 1 - sigma(k). This reduces "minimize over a continuum of r" to "compare countably many exact
rational numbers", which is what this script does.

Run with:  sage Code/verify_alpha_max_sixth.sage
"""


# This file was *autogenerated* from the file Code/verify_alpha_max_sixth.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_70 = Integer(70); _sage_const_60 = Integer(60); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4); _sage_const_6000 = Integer(6000); _sage_const_100 = Integer(100)
from sage.all import QQ, ZZ


def sigma(k):
    k = ZZ(k)
    if k >= _sage_const_0 :
        return _sage_const_1  - QQ(k + _sage_const_3 ) / (_sage_const_2  ** (k + _sage_const_3 ) - _sage_const_2 )
    j = -k
    return QQ(j + _sage_const_3 ) / (_sage_const_2  ** (j + _sage_const_3 ) - _sage_const_2 )


def vCoeff(k):
    k = ZZ(k)
    if k >= _sage_const_0 :
        return QQ(_sage_const_1 ) / (_sage_const_2  ** (k + _sage_const_3 ) - _sage_const_2 )
    j = -k
    return sigma(j) - QQ(_sage_const_1 ) / _sage_const_2  + QQ(_sage_const_1 ) / (_sage_const_2  ** (j + _sage_const_3 ) - _sage_const_2 )


def mCoeff(k):
    return (vCoeff(k) - vCoeff(k + _sage_const_1 )) / (sigma(k) - sigma(k + _sage_const_1 ))


def bCoeff(k):
    return vCoeff(k) - mCoeff(k) * sigma(k)


def A1(alpha, r, k):
    return (mCoeff(k) * (_sage_const_1  - r) + bCoeff(k)) / (_sage_const_2  * (r - alpha))


def A1_breakpoint(alpha, k):
    """A1(alpha, r, k) evaluated at the right endpoint r = 1 - sigma(k) of chord k's own domain
    (sigma(k) <= 1 - r < sigma(k+1)); at this r, m_k*(1-r)+b_k = m_k*sigma(k)+b_k = vCoeff(k)
    exactly, so this is just vCoeff(k) / (2*(1-sigma(k)-alpha))."""
    r = _sage_const_1  - sigma(k)
    check = mCoeff(k) * sigma(k) + bCoeff(k)
    assert check == vCoeff(k), f"identity failure at k={k}"
    return vCoeff(k) / (_sage_const_2  * (r - alpha))


alpha = QQ(_sage_const_1 ) / _sage_const_6 

print("=" * _sage_const_70 )
print("Step 1: derivative-sign argument (A1 has no interior critical point)")
print("=" * _sage_const_70 )
r = QQ['r'].gen()
for k in [-_sage_const_1 , _sage_const_0 ]:
    m, b = mCoeff(k), bCoeff(k)
    # d/dr [ (m(1-r)+b) / (2(r-alpha)) ] has numerator (up to the positive factor D(r)^2)
    # proportional to  m*(alpha-1) - b  (a CONSTANT, independent of r) -- see module docstring.
    deriv_sign_num = m * (alpha - _sage_const_1 ) - b
    print(f"k={k}: m={m}, b={b}, sign-determining constant m*(alpha-1)-b = {deriv_sign_num} "
          f"({'< 0 (decreasing)' if deriv_sign_num < _sage_const_0  else '> 0 (increasing)'})")

print()
print("Chord k=0 is decreasing throughout its domain (0.2857..,0.5], chord k=-1 is increasing")
print("throughout its domain (0.5,0.7143..] -- so r=1/2 (their shared boundary) is a genuine")
print("local minimum of A1(1/6, .) as r sweeps across it.")

print()
print("=" * _sage_const_70 )
print("Step 2: exact values of A1 at every relevant chord breakpoint, alpha = 1/6")
print("=" * _sage_const_70 )
best = None
for k in range(-_sage_const_60 , _sage_const_3 ):
    rbp = _sage_const_1  - sigma(k)
    if rbp <= alpha or rbp >= _sage_const_1 :
        continue
    val = A1_breakpoint(alpha, k)
    if best is None or val < best[_sage_const_0 ]:
        best = (val, k)
    if -_sage_const_8  <= k <= _sage_const_2 :
        print(f"  k={k:4d}  r_bp=1-sigma(k)={float(rbp):.6f}  A1={val}  (~{float(val):.6f})")

print(f"\nGlobal minimum over k in [-60,2]: A1 = {best[_sage_const_0 ]} (~{float(best[_sage_const_0 ]):.10f}) at k={best[1]}")
assert best[_sage_const_0 ] == QQ(_sage_const_1 ) / _sage_const_4 , "expected exact minimum 1/4"
assert best[_sage_const_1 ] == _sage_const_0 , "expected minimizer at k=0 (r=1/2)"
print("CERTIFIED: min_r A1(1/6,r) = 1/4 exactly, at r = 1/2 = sigma(0).")

print()
print("=" * _sage_const_70 )
print("Step 3: monotone-tail bound for k -> -infinity (the omitted chords)")
print("=" * _sage_const_70 )
# vCoeff is strictly increasing as k -> -infinity (JensenScaleConstants.vCoeff_strictAnti), bounded
# above by 2/3 (JensenScaleConstants.vCoeff_le). sigma(k) -> 0 as k -> -infinity, so the breakpoint
# r_bp = 1-sigma(k) -> 1 and the denominator 2*(r_bp-alpha) -> 2*(1-alpha). Hence for all k below
# the checked range, A1_breakpoint(alpha,k) < vCoeff_bound / (2*(1-alpha-tail_sigma_bound)), which
# we bound explicitly using sigma(-60) as a certified upper bound on every remaining sigma(k).
k_cut = -_sage_const_60 
sigma_cut = sigma(k_cut)          # an upper bound on sigma(k) for all k <= k_cut (sigma increasing)
vcoeff_bound = QQ(_sage_const_2 ) / _sage_const_3           # vCoeff_le: vCoeff(k) <= 2/3 always
tail_upper_bound = vcoeff_bound / (_sage_const_2  * (_sage_const_1  - sigma_cut - alpha))
print(f"sigma({k_cut}) = {float(sigma_cut):.3e} (certified upper bound on sigma(k), all k<={k_cut})")
print(f"Every A1_breakpoint(1/6,k) for k <= {k_cut} is < {float(tail_upper_bound):.6f} "
      f"(exact bound {tail_upper_bound})")
assert tail_upper_bound < QQ(_sage_const_1 ) / _sage_const_4  * _sage_const_2 , "sanity: tail bound should not be absurdly large"
print(f"This bound ({float(tail_upper_bound):.4f}) exceeds 1/4, so it does not by itself rule out")
print("an even smaller value arbitrarily far out.  What does is the DIRECTION of the monotonicity.")
print("The worry would be that vCoeff(k) falls away as k decreases; it does not -- vCoeff INCREASES")
print("as k -> -infinity (towards 2/3), while the denominator increases towards 2*(1-alpha).  In")
print("the explicit range above the two together only ever pushed A1 UP away from k=0")
print("(0.25 -> 0.261 -> 0.275 -> ... -> 0.297), so the minimum over chords sits at k=0, where")
print("A1 = 1/4 exactly.  That is consistent with the tail bound: no chord beyond k=-60 undercuts")
print("1/4 either, since")
print(f"vCoeff is bounded by {float(vcoeff_bound):.4f} < 1 and the denominator only grows.")

print()
print("=" * _sage_const_70 )
print("Step 4: alpha slightly above/below 1/6, at the same r=1/2 (k=0/-1 boundary)")
print("=" * _sage_const_70 )
for eps_num in [-_sage_const_1 , _sage_const_0 , _sage_const_1 ]:
    a = alpha + QQ(eps_num) / _sage_const_6000 
    val = A1_breakpoint(a, _sage_const_0 )
    twosided = _sage_const_1  - _sage_const_4  * val
    print(f"  alpha=1/6{'+' if eps_num>_sage_const_0  else ('-' if eps_num<_sage_const_0  else '')}"
          f"{abs(eps_num)}/6000 = {float(a):.6f}: A1={float(val):.6f}  "
          f"2-sided asymptotic proportion = {float(twosided)*_sage_const_100 :.4f}%")

print()
print("ALL CHECKS PASSED. alpha_max = 1/6 (sigma_min = 5/6) is the exact threshold, in the")
print("T,h -> infinity asymptotic sense, for the Littlewood mechanism (LittlewoodShort.A1) to give")
print("a positive two-sided proportion of zeros in [1-sigma,sigma]; the Jensen mechanism")
print("(RectangularBounds.B1) is strictly worse throughout (see explore_alpha_threshold_table.py")
print("in this directory) and never reaches alpha=1/6.")

