r"""
Rigorous certified verification of three numerical facts about `gamma` and `gamma_1`:

    (1)  0 < gamma^2 + 2*gamma_1
    (2)  exp(2/3) * (gamma^2 + 2*gamma_1) / 8  <=  (pi - 2) * gamma / (2*pi)
    (3)  0.15 <= gamma^2 + 2*gamma_1 <= 0.20

where `gamma` is the Euler-Mascheroni constant (`Real.eulerMascheroniConstant`) and `gamma_1`
is the first Stieltjes constant (`Definitions.stieltjesConstant1`).  Both enter the development
through the Laurent expansion `zeta(s) = 1/(s-1) + gamma - gamma_1*(s-1) + ...`: the combination
`gamma^2 + 2*gamma_1` is exactly the coefficient `a_1` of
`Background/LogDerivZetaLaurent.logDerivZetaCoeff_one`, hence the linear coefficient of
`neg_logDeriv_zeta_bound_of_claim_two`.

(1) is `Jensen/JensenBounds.stieltjes_combo_pos`; (2) is stated there as `stieltjes_combo_bound`.
(3) is `Background/LogDerivZetaLaurent.stieltjes_combo_numeric_bounds`, which the Lean now
proves outright -- `stieltjes_combo_lower_bound` (from gamma >= 0.5615 at n = 31 and
gamma_1 >= -0.076 at m = 5) and `stieltjes_combo_upper_bound` (from gamma <= 0.5851 at n = 64
and gamma_1 <= -0.0724 at m = 16) -- so for (3) this is an independent numeric check rather
than a certificate.

WHY THESE ARE THE RIGHT FACTS
-----------------------------
`integraloutside_bound_secondary` gives, for r > 0,

    c4(r) < (1/2)*log|zeta(1+r)| + log(2)/2 - (pi-2)*r*gamma/(2*pi) + r^2*(gamma^2+2*gamma_1)/8.

The last two terms may be dropped as a net non-positive correction exactly when

    r^2*(gamma^2+2*gamma_1)/8  <=  (pi-2)*r*gamma/(2*pi),

which after dividing by r > 0 (legitimate because (1) makes the left side increasing in r)
is the condition `r*(gamma^2+2*gamma_1)/8 <= (pi-2)*gamma/(2*pi)`, i.e.

    r  <=  r_max := 4*(pi-2)*gamma / (pi*(gamma^2+2*gamma_1)).

**The radius is `exp(2/3)*alpha`, not the `exp(3/2)*alpha` the source prints.**  Formalizing
Theorem \ref{thm:circularregions2} (Theorem 18) showed the source transposed the exponent: three
of its four printed constants force `log(r/alpha) = 2/3`, and the fourth
(`Ctilde1 = 3*E_{1/2}*e*B*alpha^{3/2}/2`) requires `(r/alpha)^{3/2} = e` -- both exactly
`r = exp(2/3)*alpha`.  (`x = exp(2/3)` is also the minimiser of `x^{3/2}/log(x)`, i.e. the
optimal radius for this argument, with minimum `3e/2`.)

So the largest radius that actually occurs is `exp(2/3) = 1.94773...`, far below
`r_max = 4.47353714...`, and the drop is justified for every `alpha <= 1` with a comfortable
margin -- no `alpha <= 0.998` restriction is needed.  The comparison at the source's printed
radius `exp(3/2) = 4.48168907...` is computed below too (labelled `[historical]` in the output):
it records exactly where the source's route would give out if the radius really were
`exp(3/2)*alpha`, namely at the razor-thin cutoff `alpha_max = r_max/exp(3/2)`, just under 1.

Everything is computed with arb ball arithmetic (`RealBallField` at 300 bits), so each printed
enclosure is a rigorous interval containing the true value and the final comparisons are exact
ball comparisons.  The one input not computed in arb is `gamma_1` itself, taken from mpmath and
inflated to a ball of radius 10^-60 (see below).

Run with:  sage Code/verify_stieltjes_combo_bound.sage
"""


# This file was *autogenerated* from the file /home/algie/lean-projects/ZerosInShortIntervals/Code/verify_stieltjes_combo_bound.sage
from sage.all_cmdline import *   # import sage library

_sage_const_300 = Integer(300); _sage_const_80 = Integer(80); _sage_const_1 = Integer(1); _sage_const_70 = Integer(70); _sage_const_10 = Integer(10); _sage_const_60 = Integer(60); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4)
PREC = _sage_const_300 
RBF = RealBallField(PREC)

# --- the two constants, as certified balls -------------------------------------------------
gamma = RBF(euler_gamma)
# First Stieltjes constant. Sage exposes it via mpmath's `stieltjes`; we take a high-precision
# value and inflate it to a ball with a generous (10^-60) radius, which is far more than enough
# for the ~10^-6 margins involved here.
import mpmath
mpmath.mp.dps = _sage_const_80 
g1_str = mpmath.nstr(mpmath.stieltjes(_sage_const_1 ), _sage_const_70 )
gamma1 = RBF(RealField(PREC)(g1_str)).add_error(RBF(_sage_const_10 ) ** (-_sage_const_60 ))

print("gamma   in", gamma)
print("gamma_1 in", gamma1)

K = gamma**_sage_const_2  + _sage_const_2  * gamma1
print("K = gamma^2 + 2*gamma_1 in", K)

# --- (1) positivity ------------------------------------------------------------------------
ok1 = K > _sage_const_0 
print()
print("(1)  0 < gamma^2 + 2*gamma_1                :", ok1)

# --- (2) the threshold inequality at the true maximal radius exp(2/3) -----------------------
lhs = (RBF(_sage_const_2 ) / _sage_const_3 ).exp() * K / _sage_const_8 
rhs = (RBF.pi() - _sage_const_2 ) * gamma / (_sage_const_2  * RBF.pi())
print()
print("LHS = exp(2/3)*K/8             in", lhs)
print("RHS = (pi-2)*gamma/(2*pi)      in", rhs)
ok2 = lhs <= rhs
print("(2)  LHS <= RHS                             :", ok2)
print("     margin RHS - LHS          in", rhs - lhs)

# --- the same comparison at the source's printed radius exp(3/2)*0.998: this is the branch
# --- that would be needed if the source's exponent were right, and it is the razor-thin one
lhs_old = (RBF(_sage_const_3 ) / _sage_const_2 ).exp() * RBF("0.998") * K / _sage_const_8 
print()
print("[historical] exp(3/2)*0.998*K/8 in", lhs_old)
print("[historical] <= RHS             :", lhs_old <= rhs, "  margin", rhs - lhs_old)

# --- informational: the exact threshold ----------------------------------------------------
r_max = _sage_const_4  * (RBF.pi() - _sage_const_2 ) * gamma / (RBF.pi() * K)
alpha_max = r_max / (RBF(_sage_const_3 ) / _sage_const_2 ).exp()
print()
print("r_max     = 4*(pi-2)*gamma/(pi*K)  in", r_max)
print("exp(2/3)  (the true radius bound)  in", (RBF(_sage_const_2 ) / _sage_const_3 ).exp())
print("exp(3/2)  (the source's printed r) in", (RBF(_sage_const_3 ) / _sage_const_2 ).exp())
print("alpha_max = r_max/exp(3/2)         in", alpha_max)
print("  -> with the corrected radius exp(2/3), every alpha <= 1 is fine;")
print("     with the printed radius exp(3/2), the cutoff would have been alpha_max above.")

# --- (3) the two-sided numeric bracket on K ------------------------------------------------
# This is the bracket `Background/LogDerivZetaLaurent.stieltjes_combo_numeric_bounds` asserts;
# combined with the exact identity `a_1 = gamma^2 + 2*gamma_1` (`logDerivZetaCoeff_one`) it
# supplies the `n = 1 -> 2` antitone step of Lemma \ref{lemma:logderzetabound} (Lemma 38),
# claim 2 (`logDerivZetaCoeff_one_bounds`).  Downstream that step needs
#   lower:  2*a_2 <= 0.1203948 (from claim 1) <= 0.15 <= a_1,
#   upper:  2*a_1 <= 0.40 < 1/2 < gamma = a_0   (using Mathlib's `one_half_lt_eulerMascheroniConstant`),
# so the bracket [0.15, 0.20] is what is required, with margins ~0.0375 and ~0.0125.
#
# NOTE this is the *whole* numeric content of that step.  Unlike a direct enclosure of `a_1`
# (which needs a Cauchy contour integral of `zeta'/zeta`, and hence `zeta'`, which
# `ComplexBallField` does not expose), `K` involves no evaluation of zeta at all, so this bound
# is genuinely certified rather than a high-precision floating-point computation.
lo, hi = RBF("0.15"), RBF("0.20")
ok3 = (K >= lo) and (K <= hi)
print()
print("(3)  0.15 <= gamma^2 + 2*gamma_1 <= 0.20    :", ok3)
print("     lower margin K - 0.15     in", K - lo)
print("     upper margin 0.20 - K     in", hi - K)

print()
if ok1 and ok2 and ok3:
    print("ALL CERTIFIED: `stieltjes_combo_pos`, `stieltjes_combo_bound`,")
    print("               and `stieltjes_combo_numeric_bounds` hold.")
else:
    raise AssertionError("verification FAILED")

