r"""
Rigorous(-ish) reproduction of Table \ref{tab:littlewoodshort} (Table 7) in
`ZerosInShortIntervals.tex` (the alpha/r/A_{1..6,alpha,r}/r-alpha table attached to
Theorem \ref{thm:littlewoodshort} (Theorem 32)).

**No Lean target.** The table is printed in the paper; no hypothesis-class field depends on it,
and nothing here is a certificate. What it pins down are the *values* of
`Littlewood.LittlewoodShort`'s `A1 .. A6` at the paper's optimal `r`, hence of `c1,c2,c3`
(`Jensen.JensenScaleConstants`) and `c4` (`Jensen.JensenBounds`) that feed them.

This is a cleaned-up, self-contained extraction of the working computation in the exploratory
notebook `Zero Density Short Intervals.ipynb` (cells 0, 1, 2, 8, 10 — the "Table A_R" block),
which has since been removed from `Code/` and is recoverable from git history only,
restructured to name each function after the matching Lean definition in
`ZerosInShortIntervals/Jensen/JensenScaleConstants.lean` / `ZerosInShortIntervals/Littlewood/*.lean`, so
the correspondence between this script, the tex, and the Lean formalization is explicit. It does
NOT copy the notebook's printed numbers -- every value here is recomputed from the definitions in
Theorem \ref{thm:littlewoodshort} (Theorem 32) and Proposition \ref{prop:jensen-easy}
(Proposition 8).

**Which `k = 0` chord triple.** As in the paper's tables, `vCoeff`/`vCoeffP`/`vCoeffPP` below carry
Remark \ref{rem:altcoefficients} (Remark 7)'s triple `(27/164, 0, log 66.7)`, i.e. Lean's
`Jensen/JensenScaleConstantsAlt.lean` (`vCoeffAlt`, `vCoeffPAlt`, `vCoeffPPAlt`), NOT
`JensenScaleConstants`'s main-text `(1/6, 1, log 0.611)`. See the "KNOWN DISCREPANCY" note at the
top of `JensenScaleConstants.lean` and `Code/verify_v0_triple_vs_tables.py`.

Rigor level: the `zeta`/`zeta'` evaluations and the `c1,c2,c3,c4` sums/integrals are done in
`ComplexBallField(200)` (certified ball arithmetic -- same as the original notebook), so those
carry a certified error radius. The purely rational/algebraic pieces (`sigma`, `mCoeff`, `bCoeff`,
`find_k`, the optimal-`r` search of `find_optimal_Ar`) are exact rationals; `eta` (root of
`1+eta+log(eta)=0`) is Newton-refined in `RealField(1000)` -- not literally ball-certified, but
carried at 1000 bits, i.e. error far below the 7-significant-figure table -- and its residual is
printed and asserted below `2^-180`. The final rounding (`roundup_to`) drops to Sage's default
`RR = RealField(53)`, which is still far more than the 7 printed digits need. This matches the
table's own stated "mostly rigorous" provenance -- it is not full
certified-interval-image-of-a-box verification the way `Code/verify_hcompact_boxes.sage` is (that
would need certified handling of the infinite tail sums and of `find_k`'s bisection, which is a
larger undertaking left as a follow-up).

Run with:  sage Code/verify_littlewoodshort_table.sage
"""


# This file was *autogenerated* from the file Code/verify_littlewoodshort_table.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_200 = Integer(200); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_27 = Integer(27); _sage_const_164 = Integer(164); _sage_const_667 = Integer(667); _sage_const_10 = Integer(10); _sage_const_1546 = Integer(1546); _sage_const_100 = Integer(100); _sage_const_99 = Integer(99); _sage_const_0p3 = RealNumber('0.3'); _sage_const_20 = Integer(20); _sage_const_180 = Integer(180); _sage_const_64 = Integer(64); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_198 = Integer(198); _sage_const_8 = Integer(8); _sage_const_738 = Integer(738); _sage_const_2231 = Integer(2231); _sage_const_6 = Integer(6); _sage_const_6932 = Integer(6932); _sage_const_4 = Integer(4); _sage_const_8759 = Integer(8759); _sage_const_29388 = Integer(29388); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_32 = Integer(32); _sage_const_128 = Integer(128); _sage_const_256 = Integer(256); _sage_const_512 = Integer(512); _sage_const_1024 = Integer(1024); _sage_const_2048 = Integer(2048); _sage_const_0p5000000 = RealNumber('0.5000000'); _sage_const_0p2469513 = RealNumber('0.2469513'); _sage_const_2p005451 = RealNumber('2.005451'); _sage_const_0p2201801 = RealNumber('0.2201801'); _sage_const_1p948504 = RealNumber('1.948504'); _sage_const_10p269668 = RealNumber('10.269668'); _sage_const_3p000000 = RealNumber('3.000000'); _sage_const_0p2304879 = RealNumber('0.2304879'); _sage_const_1p871754 = RealNumber('1.871754'); _sage_const_0p2055015 = RealNumber('0.2055015'); _sage_const_1p818604 = RealNumber('1.818604'); _sage_const_9p585023 = RealNumber('9.585023'); _sage_const_3p500000 = RealNumber('3.500000'); _sage_const_0p2195122 = RealNumber('0.2195122'); _sage_const_1p782623 = RealNumber('1.782623'); _sage_const_0p1957157 = RealNumber('0.1957157'); _sage_const_1p732003 = RealNumber('1.732003'); _sage_const_9p128594 = RealNumber('9.128594'); _sage_const_4p000000 = RealNumber('4.000000'); _sage_const_0p2857143 = RealNumber('0.2857143'); _sage_const_0p2045455 = RealNumber('0.2045455'); _sage_const_0p9115238 = RealNumber('0.9115238'); _sage_const_0p3971245 = RealNumber('0.3971245'); _sage_const_0p1059233 = RealNumber('0.1059233'); _sage_const_2p454546 = RealNumber('2.454546'); _sage_const_12p040681 = RealNumber('12.040681'); _sage_const_2p571429 = RealNumber('2.571429'); _sage_const_0p1923077 = RealNumber('0.1923077'); _sage_const_0p8569882 = RealNumber('0.8569882'); _sage_const_0p3733649 = RealNumber('0.3733649'); _sage_const_0p09958597 = RealNumber('0.09958597'); _sage_const_2p307693 = RealNumber('2.307693'); _sage_const_11p320299 = RealNumber('11.320299'); _sage_const_2p857143 = RealNumber('2.857143'); _sage_const_0p1833334 = RealNumber('0.1833334'); _sage_const_0p8169954 = RealNumber('0.8169954'); _sage_const_0p3559412 = RealNumber('0.3559412'); _sage_const_0p09493862 = RealNumber('0.09493862'); _sage_const_2p200000 = RealNumber('2.200000'); _sage_const_10p792018 = RealNumber('10.792018'); _sage_const_3p142858 = RealNumber('3.142858'); _sage_const_0p1764706 = RealNumber('0.1764706'); _sage_const_0p7864127 = RealNumber('0.7864127'); _sage_const_0p3426172 = RealNumber('0.3426172'); _sage_const_0p09138477 = RealNumber('0.09138477'); _sage_const_2p117648 = RealNumber('2.117648'); _sage_const_10p388039 = RealNumber('10.388039'); _sage_const_3p428572 = RealNumber('3.428572'); _sage_const_0p1710527 = RealNumber('0.1710527'); _sage_const_0p7622685 = RealNumber('0.7622685'); _sage_const_0p3320983 = RealNumber('0.3320983'); _sage_const_0p08857910 = RealNumber('0.08857910'); _sage_const_2p052632 = RealNumber('2.052632'); _sage_const_10p069108 = RealNumber('10.069108'); _sage_const_3p714286 = RealNumber('3.714286'); _sage_const_0p1666667 = RealNumber('0.1666667'); _sage_const_0p7427231 = RealNumber('0.7427231'); _sage_const_0p3235829 = RealNumber('0.3235829'); _sage_const_0p08630784 = RealNumber('0.08630784'); _sage_const_2p000000 = RealNumber('2.000000'); _sage_const_9p810926 = RealNumber('9.810926'); _sage_const_0p1630435 = RealNumber('0.1630435'); _sage_const_0p7265770 = RealNumber('0.7265770'); _sage_const_0p3165485 = RealNumber('0.3165485'); _sage_const_0p08443158 = RealNumber('0.08443158'); _sage_const_1p956522 = RealNumber('1.956522'); _sage_const_9p597645 = RealNumber('9.597645'); _sage_const_4p285715 = RealNumber('4.285715'); _sage_const_0p1600000 = RealNumber('0.1600000'); _sage_const_0p7130142 = RealNumber('0.7130142'); _sage_const_0p3106396 = RealNumber('0.3106396'); _sage_const_0p08285553 = RealNumber('0.08285553'); _sage_const_1p920001 = RealNumber('1.920001'); _sage_const_9p418489 = RealNumber('9.418489'); _sage_const_4p571429 = RealNumber('4.571429'); _sage_const_0p1230770 = RealNumber('0.1230770'); _sage_const_1p175299 = RealNumber('1.175299'); _sage_const_0p5120433 = RealNumber('0.5120433'); _sage_const_0p03779972 = RealNumber('0.03779972'); _sage_const_1p846154 = RealNumber('1.846154'); _sage_const_11p325849 = RealNumber('11.325849'); _sage_const_5p333334 = RealNumber('5.333334'); _sage_const_0p09677420 = RealNumber('0.09677420'); _sage_const_0p09937889 = RealNumber('0.09937889'); _sage_const_1p961264 = RealNumber('1.961264'); _sage_const_0p8544655 = RealNumber('0.8544655'); _sage_const_0p01794826 = RealNumber('0.01794826'); _sage_const_1p788820 = RealNumber('1.788820'); _sage_const_14p441878 = RealNumber('14.441878'); _sage_const_6p193549 = RealNumber('6.193549'); _sage_const_0p05555556 = RealNumber('0.05555556'); _sage_const_0p08311689 = RealNumber('0.08311689'); _sage_const_3p333573 = RealNumber('3.333573'); _sage_const_1p452341 = RealNumber('1.452341'); _sage_const_0p008701209 = RealNumber('0.008701209'); _sage_const_1p745455 = RealNumber('1.745455'); _sage_const_19p713406 = RealNumber('19.713406'); _sage_const_7p111112 = RealNumber('7.111112'); _sage_const_0p03149607 = RealNumber('0.03149607'); _sage_const_0p07134895 = RealNumber('0.07134895'); _sage_const_5p768613 = RealNumber('5.768613'); _sage_const_2p513217 = RealNumber('2.513217'); _sage_const_0p004266277 = RealNumber('0.004266277'); _sage_const_1p712375 = RealNumber('1.712375'); _sage_const_28p844815 = RealNumber('28.844815'); _sage_const_8p062993 = RealNumber('8.062993'); _sage_const_0p01764706 = RealNumber('0.01764706'); _sage_const_0p06246950 = RealNumber('0.06246950'); _sage_const_10p141176 = RealNumber('10.141176'); _sage_const_4p418216 = RealNumber('4.418216'); _sage_const_0p002105235 = RealNumber('0.002105235'); _sage_const_1p686677 = RealNumber('1.686677'); _sage_const_44p972432 = RealNumber('44.972432'); _sage_const_9p035295 = RealNumber('9.035295'); _sage_const_0p009784736 = RealNumber('0.009784736'); _sage_const_0p05554351 = RealNumber('0.05554351'); _sage_const_18p069007 = RealNumber('18.069007'); _sage_const_7p872142 = RealNumber('7.872142'); _sage_const_0p001042787 = RealNumber('0.001042787'); _sage_const_1p666306 = RealNumber('1.666306'); _sage_const_73p905261 = RealNumber('73.905261'); _sage_const_10p019570 = RealNumber('10.019570'); _sage_const_0p005376345 = RealNumber('0.005376345'); _sage_const_0p04999512 = RealNumber('0.04999512'); _sage_const_32p559922 = RealNumber('32.559922'); _sage_const_14p185413 = RealNumber('14.185413'); _sage_const_5p177350en4 = RealNumber('5.177350e-4'); _sage_const_1p649839 = RealNumber('1.649839'); _sage_const_126p451532 = RealNumber('126.451532'); _sage_const_11p010753 = RealNumber('11.010753'); _sage_const_1en30 = RealNumber('1e-30'); _sage_const_1en5 = RealNumber('1e-5')
N = _sage_const_1000 
R = ComplexBallField(_sage_const_200 )

# ---------------------------------------------------------------------------------------------
# `sigma`, `vCoeff`, `vCoeffP`, `vCoeffPP`, `mCoeff`, `bCoeff` -- `JensenScaleConstants.lean`,
# with the `k = 0` values of `JensenScaleConstantsAlt.lean`.
# ---------------------------------------------------------------------------------------------


def sigma(k):
    if k == infinity:
        return _sage_const_1 
    elif k == -infinity:
        return _sage_const_0 
    elif k == _sage_const_0 :
        return QQ(_sage_const_1 ) / _sage_const_2 
    elif k > _sage_const_0 :
        return _sage_const_1  - (k + _sage_const_3 ) / (_sage_const_2  ** (k + _sage_const_3 ) - _sage_const_2 )
    else:
        return (-k + _sage_const_3 ) / (_sage_const_2  ** (-k + _sage_const_3 ) - _sage_const_2 )


def find_k(sig, Nn=N):
    r"""`k` with `sigma(k) <= sig < sigma(k+1)` (bisection on the monotone `sigma`)."""
    upper, lower = Nn, -Nn
    vupper, vlower = sigma(upper), sigma(lower)
    if sig > vupper:
        return infinity
    if sig < vlower:
        return -infinity
    while upper - lower > _sage_const_1 :
        mid = (upper + lower) // _sage_const_2 
        vmid = sigma(mid)
        if sig < vmid:
            upper, vupper = mid, vmid
        elif sig > vmid:
            lower, vlower = mid, vmid
        else:
            return mid
    return lower


def vCoeff(k):
    # `k = 0` uses Remark \ref{rem:altcoefficients} (Remark 7), which follows the `v_k` definitions
    # after \eqref{eq:sigmak}: `v_0 = 27/164`, not `1/6` -- Lean's
    # `JensenScaleConstantsAlt.vCoeffAlt`, and what `JensenScaleConstants.lean`'s "KNOWN
    # DISCREPANCY" note records the paper's *tables* as using.
    if k == infinity:
        return _sage_const_0 
    elif k == -infinity:
        return QQ(_sage_const_1 ) / _sage_const_2 
    elif k == _sage_const_0 :
        return QQ(_sage_const_27 ) / _sage_const_164 
    elif k > _sage_const_0 :
        return _sage_const_1  / (_sage_const_2  ** (k + _sage_const_3 ) - _sage_const_2 )
    else:
        return QQ(_sage_const_1 ) / _sage_const_2  - sigma(k) + _sage_const_1  / (_sage_const_2  ** (-k + _sage_const_3 ) - _sage_const_2 )


def vCoeffP(k):
    return _sage_const_0  if k == _sage_const_0  else _sage_const_1 


def vCoeffPP(k):
    if k == _sage_const_0 :
        return log(R(_sage_const_667 ) / _sage_const_10 )  # log(66.7) = `vCoeffPPAlt 0`, the variant matching v_0 = 27/164
    elif k > _sage_const_0 :
        return log(R(_sage_const_1546 ) / _sage_const_1000 )
    else:
        return log(R(_sage_const_1546 ) / _sage_const_1000 ) + (sigma(k) - QQ(_sage_const_1 ) / _sage_const_2 ) * log(R(pi))


# CONVENTION (do not change without changing every evaluation site below):
# matches `eq:mk`/`eq:mkp`/`eq:mkpp` in the tex and `JensenScaleConstants.lean`'s
# `mCoeff`/`bCoeff` EXACTLY -- note the NEGATIVE denominator `sigma(k) - sigma(k+1)`.
# The chord is `mCoeff(k)*sigma + bCoeff(k)`, evaluated at `sigma` itself (NOT at `1-sigma`);
# it interpolates `(sigma_k, v_k) -> (sigma_{k+1}, v_{k+1})`.
def mCoeff(k):
    if k in (infinity, -infinity):
        return _sage_const_0 
    return (vCoeff(k) - vCoeff(k + _sage_const_1 )) / (sigma(k) - sigma(k + _sage_const_1 ))


def mCoeffP(k):
    if k in (infinity, -infinity):
        return _sage_const_0 
    return (vCoeffP(k) - vCoeffP(k + _sage_const_1 )) / (sigma(k) - sigma(k + _sage_const_1 ))


def mCoeffPP(k):
    if k in (infinity, -infinity):
        return _sage_const_0 
    return (vCoeffPP(k) - vCoeffPP(k + _sage_const_1 )) / (sigma(k) - sigma(k + _sage_const_1 ))


def bCoeff(k):
    return vCoeff(k) - mCoeff(k) * sigma(k)


def bCoeffP(k):
    return vCoeffP(k) - mCoeffP(k) * sigma(k)


def bCoeffPP(k):
    return vCoeffPP(k) - mCoeffPP(k) * sigma(k)


# ---------------------------------------------------------------------------------------------
# `c1(r), c2(r), c3(r)` -- the rapidly-convergent sum of `JensenScaleConstants.lean` -- and
# `c4(r)` -- the `zeta'/zeta` integral of `JensenBounds.lean`'s `c4` -- both via ball
# arithmetic, following `coef`/`c4r` in the notebook.
# ---------------------------------------------------------------------------------------------


def coef(r):
    r"""Returns `[r, c1(r), c2(r), c3(r)]`, summing the boundary term plus the tail from
    `k = find_k(1-r)+1` up to `k = N` (the terms decay geometrically in `k`, so truncating at
    `N = 1000` is far beyond the ~7-significant-figure precision the table prints)."""
    k = find_k(_sage_const_1  - r) + _sage_const_1 
    if k < -N:
        k = -N
    C1 = C2 = C3 = R(_sage_const_0 )
    thetak = R(pi / _sage_const_2 )
    thetakp1 = (arcsin(R((_sage_const_1  - sigma(k)) / r))).real()
    while k < N:
        # `(m_k + b_k)*dtheta + m_k*r*dcos` -- exactly the sum printed in the tex after
        # \eqref{eq:thetak}, in the tex/Lean chord convention fixed above.
        cosdiff = cos(thetak) - cos(thetakp1)
        thetadiff = thetak - thetakp1
        C1 += r * cosdiff * mCoeff(k - _sage_const_1 ) + thetadiff * (mCoeff(k - _sage_const_1 ) + bCoeff(k - _sage_const_1 ))
        C2 += r * cosdiff * mCoeffP(k - _sage_const_1 ) + thetadiff * (mCoeffP(k - _sage_const_1 ) + bCoeffP(k - _sage_const_1 ))
        C3 += r * cosdiff * mCoeffPP(k - _sage_const_1 ) + thetadiff * (mCoeffPP(k - _sage_const_1 ) + bCoeffPP(k - _sage_const_1 ))
        thetak = thetakp1
        k += _sage_const_1 
        thetakp1 = arcsin(R((_sage_const_1  - sigma(k)) / r)).real()
    return [r, R(C1), R(C2), R(C3)]


def integrable_logderzetaarcsin(rr, u, analytic):
    if analytic and u.real() > _sage_const_1  and u.imag().contains_zero():
        return CBF(NaN)
    return -rr * zetaderiv(_sage_const_1 , _sage_const_1  + rr * u) / zeta(_sage_const_1  + rr * u) * arcsin(u)


def c4r(r):
    r"""`c4(r) = (1/2) log zeta(1+r) - (r/pi) int_0^1 (zeta'/zeta)(1+ru) arcsin(u) du`, matching
    `JensenBounds.lean`'s `c4` (Proposition \ref{prop:integraloutside}, Proposition 15),
    integrated by certified ball quadrature (the `1/2^100` inner cutoff
    absorbs the integrable singularity of `zeta'/zeta` at `u=0`, bounded there by `arcsin(u) < 2u`,
    same as the notebook's `c4r`)."""
    val1 = R(log(zeta(_sage_const_1  + r)) / _sage_const_2 )
    val2 = (
        R.integral(lambda z, a: integrable_logderzetaarcsin(r, z, a), _sage_const_1  / _sage_const_2  ** _sage_const_100 , _sage_const_1 )
        + _sage_const_1  / _sage_const_2  ** _sage_const_99 
    ).real() / R(pi)
    return val1 + val2


# ---------------------------------------------------------------------------------------------
# `eta` -- Definitions.lean's `eta`, the root of `1 + eta + log(eta) = 0` -- Newton-refined.
# ---------------------------------------------------------------------------------------------

RR1000 = RealField(_sage_const_1000 )
_x = RR1000(_sage_const_0p3 )
__tmp__=var("t"); _f = symbolic_expression(_sage_const_1  + t + log(t)).function(t)
_df = _f.derivative()
for _ in range(_sage_const_20 ):
    _x = _x - _f(_x) / _df(_x)
eta = R(_x)
eta_residual = (_sage_const_1  + eta + log(eta)).real()
print("eta =", RR(_x), " residual of 1+eta+log(eta) at eta:", eta_residual)
assert eta_residual.abs().upper() < RR(_sage_const_2 ) ** (-_sage_const_180 ),     "eta failed to converge to the required precision"


# ---------------------------------------------------------------------------------------------
# `Phi(z) = int_z^oo log(zeta(x)) dx`, appearing in `A6` -- ported as-is
# from the notebook (cells 0/1): a certified tail via `R.integral` out to `x=1000`, plus a
# certified-from-10^6-onward prime-power-sum bound for the piece beyond `x=1000`.
# ---------------------------------------------------------------------------------------------


def prime_power_heap_iterator(limit):
    from heapq import heappush, heappop, heapify

    pq = []
    max_k = ceil(log(limit) / log(_sage_const_2 ))
    for k in range(_sage_const_1 , max_k + _sage_const_1 ):
        it = (p ** k for p in primes(ceil(limit ** (_sage_const_1  / k))) if p ** k <= limit)
        try:
            first_val = next(it)
            pq.append((first_val, it, k))
        except StopIteration:
            break
    heapify(pq)
    while pq:
        val, it, k = heappop(pq)
        yield val
        try:
            nxt = next(it)
            heappush(pq, (nxt, it, k))
        except StopIteration:
            pass


def Phi_approx(X, z):
    sumval = _sage_const_0 
    r = z - _sage_const_1 
    for n in prime_power_heap_iterator(X):
        pp = is_prime_power(n, get_data=True)
        if pp[_sage_const_1 ] > _sage_const_0 :
            sumval += R(_sage_const_1  / pp[_sage_const_1 ] / log(n) / n ** (_sage_const_1  + r))
    if X >= _sage_const_10  ** _sage_const_10 :
        epsilon = _sage_const_64  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_9 :
        epsilon = _sage_const_198  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_8 :
        epsilon = _sage_const_738  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_7 :
        epsilon = _sage_const_2231  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_6 :
        epsilon = _sage_const_6932  * _sage_const_10  ** (-_sage_const_7 )
    else:
        X = _sage_const_10  ** _sage_const_4 
        epsilon = _sage_const_8759  * _sage_const_10  ** (-_sage_const_6 )
    if r == _sage_const_0 :
        tail = R((_sage_const_1  / log(X) + _sage_const_1  / log(X) ** _sage_const_2 ) * (_sage_const_1  + epsilon))
    else:
        tail = R(
            (r ** _sage_const_2  * gamma_inc(-_sage_const_2 , R(r) * R(log(X))) + r * gamma_inc(-_sage_const_1 , R(r) * R(log(X))))
            * (r + _sage_const_1 )
            * (_sage_const_1  + epsilon)
        )
    return (sumval + tail).real()


def integrable_logzeta(z, analytic):
    if analytic and z.real() < _sage_const_0  and z.imag().contains_zero():
        return CBF(NaN)
    return log(zeta(z))


def Phi(z):
    if z == _sage_const_1 :
        val1 = R.integral(integrable_logzeta, z + _sage_const_1  / _sage_const_2  ** _sage_const_100 , _sage_const_1000 )
        val2 = R(-(_sage_const_1  / _sage_const_2  ** _sage_const_100 ) * (log(_sage_const_1  / _sage_const_2  ** _sage_const_100 ) - _sage_const_1 ))
    else:
        val1 = R.integral(integrable_logzeta, z, _sage_const_1000 )
        val2 = _sage_const_0 
    val3 = Phi_approx(_sage_const_10  ** _sage_const_6 , _sage_const_1000 )
    return val1 + val2 + val3


# ---------------------------------------------------------------------------------------------
# `A1 .. A6`, `r/alpha` -- `Littlewood/LittlewoodShort.lean`'s `A1 .. A6` (Theorem
# \ref{thm:littlewoodshort}, Theorem 32), at the optimal `r` --
# following `find_optimal_Ar` in the notebook: `r = 1 - sigma(k)` for the least `k` past which the
# ratio `v_{k+1}/(1-sigma(k+1)-alpha)` stops decreasing.
# ---------------------------------------------------------------------------------------------


def find_optimal_Ar(alpha):
    k = -_sage_const_1000 
    while (
        alpha < (_sage_const_1  - sigma(k + _sage_const_1 ))
        and (vCoeff(k + _sage_const_1 ) / (_sage_const_1  - sigma(k + _sage_const_1 ) - alpha) < vCoeff(k) / (_sage_const_1  - sigma(k) - alpha))
    ):
        k = k + _sage_const_1 
    r = _sage_const_1  - sigma(k)
    # `A1..A3` have denominator `2(r-alpha)` -- the extra `/2` is written out on each line below --
    # while `A4..A6` have denominator `(r-alpha)` alone. That asymmetry is in the tex and in Lean.
    # `A1 = (m_k(1-r)+b_k)/(2(r-alpha))` collapses to `vCoeff(k)/(2(r-alpha))` here because
    # `r = 1-sigma(k)` is a chord endpoint: `1-r = sigma(k)`, so `m_k*sigma(k)+b_k = v_k` exactly
    # and the slope never has to be evaluated. Likewise for `A2`, `A3`.
    weight = r - alpha
    A1 = vCoeff(k) / weight / _sage_const_2 
    A2 = vCoeffP(k) / pi / weight / _sage_const_2 
    A3 = vCoeffPP(k) / pi / weight / _sage_const_2 
    cr = coef(r)
    c4 = c4r(r)
    A4 = r * cr[_sage_const_1 ] / weight
    A5 = r * (cr[_sage_const_2 ] / pi + _sage_const_1 ) / weight
    A6 = (
        r * (cr[_sage_const_3 ] / pi + c4 + log(R(_sage_const_29388 ) / _sage_const_1000 ) + ((_sage_const_1  + eta) * log(zeta(_sage_const_1  + eta * r))) / pi)
        + Phi(_sage_const_1  + eta * r) / pi
    ) / weight
    return [alpha, r, A1, A2, A3, A4, A5, A6, r / alpha]


def roundup_to(v, ndig):
    r"""Round `v` UP to `ndig` significant decimal digits -- matching the tex's stated "rounded
    up" convention (and the notebook's `roundup_s`), returned as a Sage `RR = RealField(53)` value
    for easy printing/comparison."""
    v = RR(v)
    if v == _sage_const_0 :
        return RR(_sage_const_0 )
    d = ceil(log(v) / log(_sage_const_10 ))
    if d < _sage_const_1 :
        scaled = ceil(v * _sage_const_10  ** (_sage_const_1  + _sage_const_7  - d)) / _sage_const_10  ** (_sage_const_1  + _sage_const_7  - d)
    else:
        scaled = ceil(v * _sage_const_10  ** _sage_const_7 ) / _sage_const_10  ** _sage_const_7 
    return RR(scaled)


# ---------------------------------------------------------------------------------------------
# The table itself: Table \ref{tab:littlewoodshort} (Table 7) of
# `ZerosInShortIntervals.tex`, columns
# `alpha, r, A1, A2, A3, A4, A5, A6, r/alpha` -- 7 significant figures, rounded up.
# ---------------------------------------------------------------------------------------------

TABLE_ALPHA = [
    QQ(_sage_const_1 ) / _sage_const_6 , QQ(_sage_const_1 ) / _sage_const_7 , QQ(_sage_const_1 ) / _sage_const_8 , QQ(_sage_const_1 ) / _sage_const_9 , QQ(_sage_const_1 ) / _sage_const_10 , QQ(_sage_const_1 ) / _sage_const_11 , QQ(_sage_const_1 ) / _sage_const_12 , QQ(_sage_const_1 ) / _sage_const_13 ,
    QQ(_sage_const_1 ) / _sage_const_14 , QQ(_sage_const_1 ) / _sage_const_15 , QQ(_sage_const_1 ) / _sage_const_16 , QQ(_sage_const_1 ) / _sage_const_32 , QQ(_sage_const_1 ) / _sage_const_64 , QQ(_sage_const_1 ) / _sage_const_128 , QQ(_sage_const_1 ) / _sage_const_256 ,
    QQ(_sage_const_1 ) / _sage_const_512 , QQ(_sage_const_1 ) / _sage_const_1024 , QQ(_sage_const_1 ) / _sage_const_2048 ,
]

# tex row: [r, A1, A2, A3, A4, A5, A6, r/alpha]  (alpha itself is exact, printed as "1/n")
TEX_TABLE = {
    QQ(_sage_const_1 ) / _sage_const_6 : [_sage_const_0p5000000 , _sage_const_0p2469513 , _sage_const_0 , _sage_const_2p005451 , _sage_const_0p2201801 , _sage_const_1p948504 , _sage_const_10p269668 , _sage_const_3p000000 ],
    QQ(_sage_const_1 ) / _sage_const_7 : [_sage_const_0p5000000 , _sage_const_0p2304879 , _sage_const_0 , _sage_const_1p871754 , _sage_const_0p2055015 , _sage_const_1p818604 , _sage_const_9p585023 , _sage_const_3p500000 ],
    QQ(_sage_const_1 ) / _sage_const_8 : [_sage_const_0p5000000 , _sage_const_0p2195122 , _sage_const_0 , _sage_const_1p782623 , _sage_const_0p1957157 , _sage_const_1p732003 , _sage_const_9p128594 , _sage_const_4p000000 ],
    QQ(_sage_const_1 ) / _sage_const_9 : [_sage_const_0p2857143 , _sage_const_0p2045455 , _sage_const_0p9115238 , _sage_const_0p3971245 , _sage_const_0p1059233 , _sage_const_2p454546 , _sage_const_12p040681 ,
                _sage_const_2p571429 ],
    QQ(_sage_const_1 ) / _sage_const_10 : [_sage_const_0p2857143 , _sage_const_0p1923077 , _sage_const_0p8569882 , _sage_const_0p3733649 , _sage_const_0p09958597 , _sage_const_2p307693 , _sage_const_11p320299 ,
                 _sage_const_2p857143 ],
    QQ(_sage_const_1 ) / _sage_const_11 : [_sage_const_0p2857143 , _sage_const_0p1833334 , _sage_const_0p8169954 , _sage_const_0p3559412 , _sage_const_0p09493862 , _sage_const_2p200000 , _sage_const_10p792018 ,
                 _sage_const_3p142858 ],
    QQ(_sage_const_1 ) / _sage_const_12 : [_sage_const_0p2857143 , _sage_const_0p1764706 , _sage_const_0p7864127 , _sage_const_0p3426172 , _sage_const_0p09138477 , _sage_const_2p117648 , _sage_const_10p388039 ,
                 _sage_const_3p428572 ],
    QQ(_sage_const_1 ) / _sage_const_13 : [_sage_const_0p2857143 , _sage_const_0p1710527 , _sage_const_0p7622685 , _sage_const_0p3320983 , _sage_const_0p08857910 , _sage_const_2p052632 , _sage_const_10p069108 ,
                 _sage_const_3p714286 ],
    QQ(_sage_const_1 ) / _sage_const_14 : [_sage_const_0p2857143 , _sage_const_0p1666667 , _sage_const_0p7427231 , _sage_const_0p3235829 , _sage_const_0p08630784 , _sage_const_2p000000 , _sage_const_9p810926 ,
                 _sage_const_4p000000 ],
    QQ(_sage_const_1 ) / _sage_const_15 : [_sage_const_0p2857143 , _sage_const_0p1630435 , _sage_const_0p7265770 , _sage_const_0p3165485 , _sage_const_0p08443158 , _sage_const_1p956522 , _sage_const_9p597645 ,
                 _sage_const_4p285715 ],
    QQ(_sage_const_1 ) / _sage_const_16 : [_sage_const_0p2857143 , _sage_const_0p1600000 , _sage_const_0p7130142 , _sage_const_0p3106396 , _sage_const_0p08285553 , _sage_const_1p920001 , _sage_const_9p418489 ,
                 _sage_const_4p571429 ],
    QQ(_sage_const_1 ) / _sage_const_32 : [_sage_const_0p1666667 , _sage_const_0p1230770 , _sage_const_1p175299 , _sage_const_0p5120433 , _sage_const_0p03779972 , _sage_const_1p846154 , _sage_const_11p325849 ,
                 _sage_const_5p333334 ],
    QQ(_sage_const_1 ) / _sage_const_64 : [_sage_const_0p09677420 , _sage_const_0p09937889 , _sage_const_1p961264 , _sage_const_0p8544655 , _sage_const_0p01794826 , _sage_const_1p788820 , _sage_const_14p441878 ,
                 _sage_const_6p193549 ],
    QQ(_sage_const_1 ) / _sage_const_128 : [_sage_const_0p05555556 , _sage_const_0p08311689 , _sage_const_3p333573 , _sage_const_1p452341 , _sage_const_0p008701209 , _sage_const_1p745455 , _sage_const_19p713406 ,
                  _sage_const_7p111112 ],
    QQ(_sage_const_1 ) / _sage_const_256 : [_sage_const_0p03149607 , _sage_const_0p07134895 , _sage_const_5p768613 , _sage_const_2p513217 , _sage_const_0p004266277 , _sage_const_1p712375 , _sage_const_28p844815 ,
                  _sage_const_8p062993 ],
    QQ(_sage_const_1 ) / _sage_const_512 : [_sage_const_0p01764706 , _sage_const_0p06246950 , _sage_const_10p141176 , _sage_const_4p418216 , _sage_const_0p002105235 , _sage_const_1p686677 , _sage_const_44p972432 ,
                  _sage_const_9p035295 ],
    QQ(_sage_const_1 ) / _sage_const_1024 : [_sage_const_0p009784736 , _sage_const_0p05554351 , _sage_const_18p069007 , _sage_const_7p872142 , _sage_const_0p001042787 , _sage_const_1p666306 , _sage_const_73p905261 ,
                   _sage_const_10p019570 ],
    QQ(_sage_const_1 ) / _sage_const_2048 : [_sage_const_0p005376345 , _sage_const_0p04999512 , _sage_const_32p559922 , _sage_const_14p185413 , _sage_const_5p177350en4 , _sage_const_1p649839 ,
                   _sage_const_126p451532 , _sage_const_11p010753 ],
}

COLS = ["r", "A1", "A2", "A3", "A4", "A5", "A6", "r/alpha"]

print("\n=== Reproducing Table tab:littlewoodshort ===\n")
worst_rel_gap = _sage_const_0 
for alpha in TABLE_ALPHA:
    computed = find_optimal_Ar(alpha)  # [alpha, r, A1, A2, A3, A4, A5, A6, r/alpha]
    printed = TEX_TABLE[alpha]
    print(f"alpha = 1/{QQ(_sage_const_1 )/alpha} :")
    for name, comp, want in zip(COLS, computed[_sage_const_1 :], printed):
        comp_r = RR(comp)
        rounded = roundup_to(comp_r, _sage_const_7 )
        gap = abs(RR(want) - rounded) / max(abs(RR(want)), _sage_const_1en30 )
        worst_rel_gap = max(worst_rel_gap, gap)
        flag = "" if gap < _sage_const_1en5  else "   <-- MISMATCH"
        print(f"    {name:8s} computed={comp_r:.10g}  roundup7={rounded:.10g}"
              f"  tex={want:.10g}{flag}")
    print()

print(f"Worst relative gap between our rounded-up value and the tex's printed value:"
      f" {worst_rel_gap:.3e}")
print("(Expected to be tiny -- both this script and the tex value trace back to the same"
      " ball-arithmetic computation in the notebook; a large gap would flag either a genuine"
      " numeric error in the tex or a divergence in how this script ported the definitions.)")

