r"""
Rigorous(-ish) reproduction of the five Jensen / rectangular-Jensen constant tables of
`ZerosInShortIntervals.tex`: Tables \ref{tab:crvalues} (Table 2), \ref{tab:CRvalues}
(Table 3), \ref{tab:crvalues2} (Table 4), \ref{tab:rectangularjensen} (Table 5) and
\ref{tab:crvalues3} (Table 6). Table \ref{tab:littlewoodshort} (Table 7) is covered separately by
`verify_littlewoodshort_table.sage`, whose `coef`/`c4r`/`sigma`/`mCoeff`/`bCoeff`/`Phi` machinery
this script reuses verbatim -- see that file's docstring for the shared provenance/rigor notes.

NUMBERING NOTE: the identifiers (`TABLE1_R`, `TEX_TABLE1`, ..., `worst5`) and the banners/printed
labels below number these five tables 1-5, in the order this script does them. The tex numbers
them 2-6. The `\ref` labels are the stable identifier; the ordinals are not.

**No Lean target.** These tables are printed in the paper; no hypothesis-class field depends on
them, and nothing here is a certificate. What they pin down are the *values* of the Lean constants
`c1,c2,c3` (`Jensen.JensenScaleConstants`), `c4` and `C1,C2,C3` (`Jensen.JensenBounds`), and `c5`,
`rectDenom`, `B1..B4` (`Jensen.RectangularBounds`).

Values are recomputed from the definitions in Proposition \ref{prop:jensen-easy} (Proposition 8;
`c1,c2,c3`), Proposition \ref{prop:integraloutside} (Proposition 15; `c4`), Proposition
\ref{prop:outside3} (Proposition 23; `c5`), Theorem \ref{thm:circularregions1} (Theorem 16;
`C1,C2,C3`) and Theorem \ref{thm:rectangularjensen} (Theorem 24; `B1,B2,B3,B4`). Not copied from
the notebook's printed numbers.

**Which `k = 0` chord triple.** As in the paper's tables, `vCoeff`/`vCoeffP`/`vCoeffPP` below carry
the Remark \ref{rem:altcoefficients} (Remark 7) triple `(v_0, v_0', v_0'') = (27/164, 0, log 66.7)`
-- in Lean, `Jensen/JensenScaleConstantsAlt.lean`'s `vCoeffAlt`, `vCoeffPAlt`, `vCoeffPPAlt`.
`JensenScaleConstants`'s own `vCoeff`/`vCoeffP`/`vCoeffPP` are the main-text triple
`(1/6, 1, log 0.611)`, so `JensenBounds.c1,c2,c3` evaluate to different numbers than the ones
reproduced here. That is deliberate and is recorded as the "KNOWN DISCREPANCY" note at the top of
`JensenScaleConstants.lean`; see also `Code/verify_v0_triple_vs_tables.py`.

**Rigor level, per quantity:**
  * `c1,c2,c3,c4` at a *given* `r`: `ComplexBallField(200)` certified ball arithmetic (as in
    `verify_littlewoodshort_table.sage`).
  * `c5` at a given `r`: same, via a new certified-ball quadrature of
    `(2r/pi) int_0^1 log(zeta(1+ru)) arcsin(u) du` (the `u=0` endpoint is handled the same way as
    `c4r`'s `zeta'/zeta` singularity there, via a `1/2^100` cutoff -- `log(zeta(1+ru))*arcsin(u) ->
    0` there since `arcsin(u) ~ u` beats the `log(1/u)` blowup of `log(zeta(1+ru))` as `u -> 0`).
  * The optimal `r` in Tables `CRvalues`/`rectangularjensen` (minimizing `C1(alpha,r)` /
    `B1(alpha,r)` over `r in (alpha, 1)`): a golden-section search whose bracket arithmetic is
    `RF = RealField(200)` but whose objective is `c1_fast`, a *fast* `RD = RealField(53)`
    (non-ball), 80-term-capped evaluation of `c1(r)` alone (for speed -- the search only needs
    the location of the minimum, not a certified value there), then one final certified
    `ComplexBallField(200)` evaluation of `c1,c2,c3,c4,c5` at the converged `r*`. This mirrors the
    notebook's own two-tier `coef1` (fast search) / `coef` (certified) split. The search itself is
    NOT a certified global-optimality proof (matching this project's "mostly rigorous" standard for
    tables, not the full certified-box standard of `verify_hcompact_boxes.sage`); `c1(r)` is smooth
    and unimodal in `r` on the ranges tested here (verified empirically by the search converging to
    the same point from multiple starting brackets), so this is a reasonable, not fully certified,
    optimum.
  * The assembly of `C1,C2,C3` and `B1..B4` from the `c_i`, together with `rectDenom` and
    `roundup_to`, runs in plain `RF = RealField(200)`, not in ball arithmetic. So the numbers this
    script prints and compares are 200-bit approximations, not enclosures.

Run with:  sage Code/verify_circular_rectangular_tables.sage
"""


# This file was *autogenerated* from the file /home/algie/lean-projects/ZerosInShortIntervals/Code/verify_circular_rectangular_tables.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1000 = Integer(1000); _sage_const_200 = Integer(200); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_27 = Integer(27); _sage_const_164 = Integer(164); _sage_const_667 = Integer(667); _sage_const_10 = Integer(10); _sage_const_1546 = Integer(1546); _sage_const_53 = Integer(53); _sage_const_80 = Integer(80); _sage_const_100 = Integer(100); _sage_const_99 = Integer(99); _sage_const_64 = Integer(64); _sage_const_7 = Integer(7); _sage_const_9 = Integer(9); _sage_const_198 = Integer(198); _sage_const_8 = Integer(8); _sage_const_738 = Integer(738); _sage_const_2231 = Integer(2231); _sage_const_6 = Integer(6); _sage_const_6932 = Integer(6932); _sage_const_4 = Integer(4); _sage_const_8759 = Integer(8759); _sage_const_29388 = Integer(29388); _sage_const_1p7975699586287395 = RealNumber('1.7975699586287395'); _sage_const_5 = Integer(5); _sage_const_45 = Integer(45); _sage_const_1p001 = RealNumber('1.001'); _sage_const_0p999999 = RealNumber('0.999999'); _sage_const_1en30 = RealNumber('1e-30'); _sage_const_1en4 = RealNumber('1e-4'); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_32 = Integer(32); _sage_const_128 = Integer(128); _sage_const_256 = Integer(256); _sage_const_512 = Integer(512); _sage_const_1024 = Integer(1024); _sage_const_2048 = Integer(2048); _sage_const_0p4260491 = RealNumber('0.4260491'); _sage_const_1p320694 = RealNumber('1.320694'); _sage_const_1p233886 = RealNumber('1.233886'); _sage_const_0p5099522 = RealNumber('0.5099522'); _sage_const_0p8331601 = RealNumber('0.8331601'); _sage_const_0p1467868 = RealNumber('0.1467868'); _sage_const_0p9393432 = RealNumber('0.9393432'); _sage_const_3p061478 = RealNumber('3.061478'); _sage_const_0p7795712 = RealNumber('0.7795712'); _sage_const_1p126439 = RealNumber('1.126439'); _sage_const_0p08122972 = RealNumber('0.08122972'); _sage_const_1p491029 = RealNumber('1.491029'); _sage_const_0p9846382 = RealNumber('0.9846382'); _sage_const_0p9546469 = RealNumber('0.9546469'); _sage_const_1p271554 = RealNumber('1.271554'); _sage_const_0p05402652 = RealNumber('0.05402652'); _sage_const_1p570797 = RealNumber('1.570797'); _sage_const_0p6843504 = RealNumber('0.6843504'); _sage_const_1p084244 = RealNumber('1.084244'); _sage_const_1p360125 = RealNumber('1.360125'); _sage_const_0p03956564 = RealNumber('0.03956564'); _sage_const_1p187130 = RealNumber('1.187130'); _sage_const_1p420588 = RealNumber('1.420588'); _sage_const_0p03071227 = RealNumber('0.03071227'); _sage_const_1p272441 = RealNumber('1.272441'); _sage_const_1p464849 = RealNumber('1.464849'); _sage_const_0p02516876 = RealNumber('0.02516876'); _sage_const_1p345309 = RealNumber('1.345309'); _sage_const_1p498839 = RealNumber('1.498839'); _sage_const_0p02110448 = RealNumber('0.02110448'); _sage_const_1p408902 = RealNumber('1.408902'); _sage_const_1p525868 = RealNumber('1.525868'); _sage_const_0p01803813 = RealNumber('0.01803813'); _sage_const_1p465317 = RealNumber('1.465317'); _sage_const_1p547944 = RealNumber('1.547944'); _sage_const_0p01569390 = RealNumber('0.01569390'); _sage_const_1p516009 = RealNumber('1.516009'); _sage_const_1p566357 = RealNumber('1.566357'); _sage_const_0p01393216 = RealNumber('0.01393216'); _sage_const_1p562034 = RealNumber('1.562034'); _sage_const_1p581977 = RealNumber('1.581977'); _sage_const_0p01249892 = RealNumber('0.01249892'); _sage_const_1p604178 = RealNumber('1.604178'); _sage_const_1p595417 = RealNumber('1.595417'); _sage_const_0p01129907 = RealNumber('0.01129907'); _sage_const_1p643045 = RealNumber('1.643045'); _sage_const_1p607118 = RealNumber('1.607118'); _sage_const_0p01028337 = RealNumber('0.01028337'); _sage_const_1p679108 = RealNumber('1.679108'); _sage_const_1p617407 = RealNumber('1.617407'); _sage_const_0p009416022 = RealNumber('0.009416022'); _sage_const_1p712745 = RealNumber('1.712745'); _sage_const_1p626535 = RealNumber('1.626535'); _sage_const_0p008670644 = RealNumber('0.008670644'); _sage_const_1p744261 = RealNumber('1.744261'); _sage_const_1p634694 = RealNumber('1.634694'); _sage_const_0p003703026 = RealNumber('0.003703026'); _sage_const_2p085161 = RealNumber('2.085161'); _sage_const_1p702482 = RealNumber('1.702482'); _sage_const_0p001626574 = RealNumber('0.001626574'); _sage_const_2p428881 = RealNumber('2.428881'); _sage_const_1p743167 = RealNumber('1.743167'); _sage_const_7p256286en4 = RealNumber('7.256286e-4'); _sage_const_2p774023 = RealNumber('2.774023'); _sage_const_1p766930 = RealNumber('1.766930'); _sage_const_3p277390en4 = RealNumber('3.277390e-4'); _sage_const_3p119880 = RealNumber('3.119880'); _sage_const_1p780529 = RealNumber('1.780529'); _sage_const_1p495313en4 = RealNumber('1.495313e-4'); _sage_const_3p466095 = RealNumber('3.466095'); _sage_const_1p788188 = RealNumber('1.788188'); _sage_const_6p880172en5 = RealNumber('6.880172e-5'); _sage_const_3p812489 = RealNumber('3.812489'); _sage_const_1p792449 = RealNumber('1.792449'); _sage_const_3p188568en5 = RealNumber('3.188568e-5'); _sage_const_4p158973 = RealNumber('4.158973'); _sage_const_1p794794 = RealNumber('1.794794'); _sage_const_0p6490511 = RealNumber('0.6490511'); _sage_const_0p3264740 = RealNumber('0.3264740'); _sage_const_1p965836 = RealNumber('1.965836'); _sage_const_7p446222 = RealNumber('7.446222'); _sage_const_1p947154 = RealNumber('1.947154'); _sage_const_0p5022756 = RealNumber('0.5022756'); _sage_const_0p2117515 = RealNumber('0.2117515'); _sage_const_1p858502 = RealNumber('1.858502'); _sage_const_7p369401 = RealNumber('7.369401'); _sage_const_2p009103 = RealNumber('2.009103'); _sage_const_0p3940064 = RealNumber('0.3940064'); _sage_const_0p1538013 = RealNumber('0.1538013'); _sage_const_2p093277 = RealNumber('2.093277'); _sage_const_7p054466 = RealNumber('7.054466'); _sage_const_1p970032 = RealNumber('1.970032'); _sage_const_0p3242696 = RealNumber('0.3242696'); _sage_const_0p1170874 = RealNumber('0.1170874'); _sage_const_2p225533 = RealNumber('2.225533'); _sage_const_6p965111 = RealNumber('6.965111'); _sage_const_1p945618 = RealNumber('1.945618'); _sage_const_0p2897366 = RealNumber('0.2897366'); _sage_const_0p09333569 = RealNumber('0.09333569'); _sage_const_2p120321 = RealNumber('2.120321'); _sage_const_6p530988 = RealNumber('6.530988'); _sage_const_2p028157 = RealNumber('2.028157'); _sage_const_0p2606756 = RealNumber('0.2606756'); _sage_const_0p07783097 = RealNumber('0.07783097'); _sage_const_2p040920 = RealNumber('2.040920'); _sage_const_6p345352 = RealNumber('6.345352'); _sage_const_2p085405 = RealNumber('2.085405'); _sage_const_0p2276378 = RealNumber('0.2276378'); _sage_const_0p06616898 = RealNumber('0.06616898'); _sage_const_2p091395 = RealNumber('2.091395'); _sage_const_6p588795 = RealNumber('6.588795'); _sage_const_2p048740 = RealNumber('2.048740'); _sage_const_0p2030836 = RealNumber('0.2030836'); _sage_const_0p05706802 = RealNumber('0.05706802'); _sage_const_2p117307 = RealNumber('2.117307'); _sage_const_6p744948 = RealNumber('6.744948'); _sage_const_2p030836 = RealNumber('2.030836'); _sage_const_0p1851792 = RealNumber('0.1851792'); _sage_const_0p04988792 = RealNumber('0.04988792'); _sage_const_2p108330 = RealNumber('2.108330'); _sage_const_6p776810 = RealNumber('6.776810'); _sage_const_2p036971 = RealNumber('2.036971'); _sage_const_0p1729682 = RealNumber('0.1729682'); _sage_const_0p04420265 = RealNumber('0.04420265'); _sage_const_2p054067 = RealNumber('2.054067'); _sage_const_6p646159 = RealNumber('6.646159'); _sage_const_2p075618 = RealNumber('2.075618'); _sage_const_0p1668192 = RealNumber('0.1668192'); _sage_const_0p03972128 = RealNumber('0.03972128'); _sage_const_1p937723 = RealNumber('1.937723'); _sage_const_6p291698 = RealNumber('6.291698'); _sage_const_2p168650 = RealNumber('2.168650'); _sage_const_0p1550286 = RealNumber('0.1550286'); _sage_const_0p03611895 = RealNumber('0.03611895'); _sage_const_1p935706 = RealNumber('1.935706'); _sage_const_6p329759 = RealNumber('6.329759'); _sage_const_2p170400 = RealNumber('2.170400'); _sage_const_0p1433184 = RealNumber('0.1433184'); _sage_const_0p03302353 = RealNumber('0.03302353'); _sage_const_1p959855 = RealNumber('1.959855'); _sage_const_6p457329 = RealNumber('6.457329'); _sage_const_2p149775 = RealNumber('2.149775'); _sage_const_0p1333413 = RealNumber('0.1333413'); _sage_const_0p03033976 = RealNumber('0.03033976'); _sage_const_1p979559 = RealNumber('1.979559'); _sage_const_6p567526 = RealNumber('6.567526'); _sage_const_2p133460 = RealNumber('2.133460'); _sage_const_0p06834560 = RealNumber('0.06834560'); _sage_const_0p01242107 = RealNumber('0.01242107'); _sage_const_1p916792 = RealNumber('1.916792'); _sage_const_6p771429 = RealNumber('6.771429'); _sage_const_2p187059 = RealNumber('2.187059'); _sage_const_0p03512879 = RealNumber('0.03512879'); _sage_const_0p005269206 = RealNumber('0.005269206'); _sage_const_1p851512 = RealNumber('1.851512'); _sage_const_6p944143 = RealNumber('6.944143'); _sage_const_2p248243 = RealNumber('2.248243'); _sage_const_0p01817011 = RealNumber('0.01817011'); _sage_const_0p002295522 = RealNumber('0.002295522'); _sage_const_1p777141 = RealNumber('1.777141'); _sage_const_7p052067 = RealNumber('7.052067'); _sage_const_2p325774 = RealNumber('2.325774'); _sage_const_0p009413507 = RealNumber('0.009413507'); _sage_const_0p001021403 = RealNumber('0.001021403'); _sage_const_1p705384 = RealNumber('1.705384'); _sage_const_7p139335 = RealNumber('7.139335'); _sage_const_2p409858 = RealNumber('2.409858'); _sage_const_0p004727625 = RealNumber('0.004727625'); _sage_const_4p607252en4 = RealNumber('4.607252e-4'); _sage_const_1p696848 = RealNumber('1.696848'); _sage_const_7p492183 = RealNumber('7.492183'); _sage_const_2p420544 = RealNumber('2.420544'); _sage_const_0p002374581 = RealNumber('0.002374581'); _sage_const_2p099090en4 = RealNumber('2.099090e-4'); _sage_const_1p688169 = RealNumber('1.688169'); _sage_const_7p840865 = RealNumber('7.840865'); _sage_const_2p431570 = RealNumber('2.431570'); _sage_const_0p001192880 = RealNumber('0.001192880'); _sage_const_9p643198en5 = RealNumber('9.643198e-5'); _sage_const_1p679292 = RealNumber('1.679292'); _sage_const_8p184763 = RealNumber('8.184763'); _sage_const_2p443018 = RealNumber('2.443018'); _sage_const_120 = Integer(120); _sage_const_0p1433183 = RealNumber('0.1433183'); _sage_const_0p06834559 = RealNumber('0.06834559'); _sage_const_0p009413510 = RealNumber('0.009413510'); _sage_const_0p004727620 = RealNumber('0.004727620'); _sage_const_0p002374580 = RealNumber('0.002374580'); _sage_const_0p2175520 = RealNumber('0.2175520'); _sage_const_0p9738017 = RealNumber('0.9738017'); _sage_const_2p853749 = RealNumber('2.853749'); _sage_const_0p6729643 = RealNumber('0.6729643'); _sage_const_0p1477365 = RealNumber('0.1477365'); _sage_const_0p9319669 = RealNumber('0.9319669'); _sage_const_3p089081 = RealNumber('3.089081'); _sage_const_0p7776710 = RealNumber('0.7776710'); _sage_const_0p1042849 = RealNumber('0.1042849'); _sage_const_1p317413 = RealNumber('1.317413'); _sage_const_1p638224 = RealNumber('1.638224'); _sage_const_0p8812288 = RealNumber('0.8812288'); _sage_const_0p07793089 = RealNumber('0.07793089'); _sage_const_1p511949 = RealNumber('1.511949'); _sage_const_0p9058834 = RealNumber('0.9058834'); _sage_const_0p9668954 = RealNumber('0.9668954'); _sage_const_0p06600019 = RealNumber('0.06600019'); _sage_const_1p568710 = RealNumber('1.568710'); _sage_const_0p6922055 = RealNumber('0.6922055'); _sage_const_1p017316 = RealNumber('1.017316'); _sage_const_0p05720288 = RealNumber('0.05720288'); _sage_const_1p065177 = RealNumber('1.065177'); _sage_const_0p04745803 = RealNumber('0.04745803'); _sage_const_1p127225 = RealNumber('1.127225'); _sage_const_0p04042969 = RealNumber('0.04042969'); _sage_const_1p180019 = RealNumber('1.180019'); _sage_const_0p03549344 = RealNumber('0.03549344'); _sage_const_1p223032 = RealNumber('1.223032'); _sage_const_0p03227938 = RealNumber('0.03227938'); _sage_const_1p254995 = RealNumber('1.254995'); _sage_const_0p03074843 = RealNumber('0.03074843'); _sage_const_1p272011 = RealNumber('1.272011'); _sage_const_0p02798899 = RealNumber('0.02798899'); _sage_const_1p306581 = RealNumber('1.306581'); _sage_const_0p02527499 = RealNumber('0.02527499'); _sage_const_1p343779 = RealNumber('1.343779'); _sage_const_0p02298980 = RealNumber('0.02298980'); _sage_const_1p378087 = RealNumber('1.378087'); _sage_const_0p009720201 = RealNumber('0.009720201'); _sage_const_1p700612 = RealNumber('1.700612'); _sage_const_0p004268841 = RealNumber('0.004268841'); _sage_const_2p027367 = RealNumber('2.027367'); _sage_const_0p001937541 = RealNumber('0.001937541'); _sage_const_2p353894 = RealNumber('2.353894'); _sage_const_8p983930en4 = RealNumber('8.983930e-4'); _sage_const_2p681106 = RealNumber('2.681106'); _sage_const_4p072770en4 = RealNumber('4.072770e-4'); _sage_const_3p024609 = RealNumber('3.024609'); _sage_const_1p865119en4 = RealNumber('1.865119e-4'); _sage_const_3p368478 = RealNumber('3.368478'); _sage_const_8p613635en5 = RealNumber('8.613635e-5'); _sage_const_3p712486 = RealNumber('3.712486'); _sage_const_0p5647100 = RealNumber('0.5647100'); _sage_const_0p2457053 = RealNumber('0.2457053'); _sage_const_0p3900919 = RealNumber('0.3900919'); _sage_const_1p450119 = RealNumber('1.450119'); _sage_const_6p518765 = RealNumber('6.518765'); _sage_const_0p5463417 = RealNumber('0.5463417'); _sage_const_3p952970 = RealNumber('3.952970'); _sage_const_0p5185446 = RealNumber('0.5185446'); _sage_const_0p2294753 = RealNumber('0.2294753'); _sage_const_0p4239720 = RealNumber('0.4239720'); _sage_const_1p514935 = RealNumber('1.514935'); _sage_const_6p977388 = RealNumber('6.977388'); _sage_const_0p5032529 = RealNumber('0.5032529'); _sage_const_4p148357 = RealNumber('4.148357'); _sage_const_0p5030821 = RealNumber('0.5030821'); _sage_const_0p2172051 = RealNumber('0.2172051'); _sage_const_0p4340594 = RealNumber('0.4340594'); _sage_const_1p446353 = RealNumber('1.446353'); _sage_const_6p922300 = RealNumber('6.922300'); _sage_const_0p4906586 = RealNumber('0.4906586'); _sage_const_4p527739 = RealNumber('4.527739'); _sage_const_0p4821212 = RealNumber('0.4821212'); _sage_const_0p2079206 = RealNumber('0.2079206'); _sage_const_0p4778655 = RealNumber('0.4778655'); _sage_const_1p331336 = RealNumber('1.331336'); _sage_const_7p058488 = RealNumber('7.058488'); _sage_const_0p4716364 = RealNumber('0.4716364'); _sage_const_4p821212 = RealNumber('4.821212'); _sage_const_0p3820330 = RealNumber('0.3820330'); _sage_const_0p1991813 = RealNumber('0.1991813'); _sage_const_0p8624038 = RealNumber('0.8624038'); _sage_const_0p9519504 = RealNumber('0.9519504'); _sage_const_9p637060 = RealNumber('9.637060'); _sage_const_0p3710589 = RealNumber('0.3710589'); _sage_const_4p202362 = RealNumber('4.202362'); _sage_const_0p3390065 = RealNumber('0.3390065'); _sage_const_0p1907470 = RealNumber('0.1907470'); _sage_const_1p076388 = RealNumber('1.076388'); _sage_const_0p7557944 = RealNumber('0.7557944'); _sage_const_11p128858 = RealNumber('11.128858'); _sage_const_0p3286046 = RealNumber('0.3286046'); _sage_const_4p068078 = RealNumber('4.068078'); _sage_const_0p3165097 = RealNumber('0.3165097'); _sage_const_0p1832274 = RealNumber('0.1832274'); _sage_const_1p186113 = RealNumber('1.186113'); _sage_const_0p6552031 = RealNumber('0.6552031'); _sage_const_11p906782 = RealNumber('11.906782'); _sage_const_0p3070199 = RealNumber('0.3070199'); _sage_const_4p114626 = RealNumber('4.114626'); _sage_const_0p3035626 = RealNumber('0.3035626'); _sage_const_0p1767236 = RealNumber('0.1767236'); _sage_const_1p236003 = RealNumber('1.236003'); _sage_const_0p6023857 = RealNumber('0.6023857'); _sage_const_12p253958 = RealNumber('12.253958'); _sage_const_0p2950393 = RealNumber('0.2950393'); _sage_const_4p249876 = RealNumber('4.249876'); _sage_const_0p2957571 = RealNumber('0.2957571'); _sage_const_0p1711536 = RealNumber('0.1711536'); _sage_const_1p252382 = RealNumber('1.252382'); _sage_const_0p5730817 = RealNumber('0.5730817'); _sage_const_12p349950 = RealNumber('12.349950'); _sage_const_0p2881455 = RealNumber('0.2881455'); _sage_const_4p436356 = RealNumber('4.436356'); _sage_const_0p2909922 = RealNumber('0.2909922'); _sage_const_0p1663861 = RealNumber('0.1663861'); _sage_const_1p250289 = RealNumber('1.250289'); _sage_const_0p5551999 = RealNumber('0.5551999'); _sage_const_12p302409 = RealNumber('12.302409'); _sage_const_0p2842010 = RealNumber('0.2842010'); _sage_const_4p655874 = RealNumber('4.655874'); _sage_const_0p1701799 = RealNumber('0.1701799'); _sage_const_0p1273443 = RealNumber('0.1273443'); _sage_const_2p016620 = RealNumber('2.016620'); _sage_const_0p8785824 = RealNumber('0.8785824'); _sage_const_20p388630 = RealNumber('20.388630'); _sage_const_0p1672861 = RealNumber('0.1672861'); _sage_const_5p445757 = RealNumber('5.445757'); _sage_const_0p09924636 = RealNumber('0.09924636'); _sage_const_0p1023306 = RealNumber('0.1023306'); _sage_const_3p292282 = RealNumber('3.292282'); _sage_const_1p434352 = RealNumber('1.434352'); _sage_const_33p994587 = RealNumber('33.994587'); _sage_const_0p09800867 = RealNumber('0.09800867'); _sage_const_6p351767 = RealNumber('6.351767'); _sage_const_0p05717608 = RealNumber('0.05717608'); _sage_const_0p08524602 = RealNumber('0.08524602'); _sage_const_5p501905 = RealNumber('5.501905'); _sage_const_2p397021 = RealNumber('2.397021'); _sage_const_57p665580 = RealNumber('57.665580'); _sage_const_0p05663982 = RealNumber('0.05663982'); _sage_const_7p318538 = RealNumber('7.318538'); _sage_const_0p03250649 = RealNumber('0.03250649'); _sage_const_0p07294429 = RealNumber('0.07294429'); _sage_const_9p396536 = RealNumber('9.396536'); _sage_const_4p093798 = RealNumber('4.093798'); _sage_const_99p501950 = RealNumber('99.501950'); _sage_const_0p03227093 = RealNumber('0.03227093'); _sage_const_8p321661 = RealNumber('8.321661'); _sage_const_0p01825477 = RealNumber('0.01825477'); _sage_const_0p06370419 = RealNumber('0.06370419'); _sage_const_16p349070 = RealNumber('16.349070'); _sage_const_7p122815 = RealNumber('7.122815'); _sage_const_174p312148 = RealNumber('174.312148'); _sage_const_0p01814999 = RealNumber('0.01814999'); _sage_const_9p346441 = RealNumber('9.346441'); _sage_const_0p01014060 = RealNumber('0.01014060'); _sage_const_0p05652525 = RealNumber('0.05652525'); _sage_const_28p889451 = RealNumber('28.889451'); _sage_const_12p586295 = RealNumber('12.586295'); _sage_const_309p383987 = RealNumber('309.383987'); _sage_const_0p01009347 = RealNumber('0.01009347'); _sage_const_10p383974 = RealNumber('10.383974'); _sage_const_0p005580532 = RealNumber('0.005580532'); _sage_const_0p05079351 = RealNumber('0.05079351'); _sage_const_51p707199 = RealNumber('51.707199'); _sage_const_22p527325 = RealNumber('22.527325'); _sage_const_555p296995 = RealNumber('555.296995'); _sage_const_0p005559130 = RealNumber('0.005559130'); _sage_const_11p428930 = RealNumber('11.428930'); _sage_const_0p3820329 = RealNumber('0.3820329'); _sage_const_0p09924635 = RealNumber('0.09924635'); _sage_const_0p05717607 = RealNumber('0.05717607'); _sage_const_0p005580530 = RealNumber('0.005580530'); _sage_const_0p1761601 = RealNumber('0.1761601'); _sage_const_0p8786375 = RealNumber('0.8786375'); _sage_const_3p266227 = RealNumber('3.266227'); _sage_const_1p078532 = RealNumber('1.078532'); _sage_const_0p1548203 = RealNumber('0.1548203'); _sage_const_0p8986260 = RealNumber('0.8986260'); _sage_const_3p210968 = RealNumber('3.210968'); _sage_const_1p112301 = RealNumber('1.112301'); _sage_const_0p1480773 = RealNumber('0.1480773'); _sage_const_0p9296458 = RealNumber('0.9296458'); _sage_const_3p097724 = RealNumber('3.097724'); _sage_const_1p124066 = RealNumber('1.124066'); _sage_const_0p1394940 = RealNumber('0.1394940'); _sage_const_1p007195 = RealNumber('1.007195'); _sage_const_2p806049 = RealNumber('2.806049'); _sage_const_1p140402 = RealNumber('1.140402'); _sage_const_0p09963112 = RealNumber('0.09963112'); _sage_const_1p355212 = RealNumber('1.355212'); _sage_const_1p495928 = RealNumber('1.495928'); _sage_const_1p225349 = RealNumber('1.225349'); _sage_const_0p08331889 = RealNumber('0.08331889'); _sage_const_1p477082 = RealNumber('1.477082'); _sage_const_1p037145 = RealNumber('1.037145'); _sage_const_1p265982 = RealNumber('1.265982'); _sage_const_0p07515015 = RealNumber('0.07515015'); _sage_const_1p528325 = RealNumber('1.528325'); _sage_const_0p8442389 = RealNumber('0.8442389'); _sage_const_1p288392 = RealNumber('1.288392'); _sage_const_0p07062081 = RealNumber('0.07062081'); _sage_const_1p551699 = RealNumber('1.551699'); _sage_const_0p7562453 = RealNumber('0.7562453'); _sage_const_1p301685 = RealNumber('1.301685'); _sage_const_0p06797647 = RealNumber('0.06797647'); _sage_const_1p562641 = RealNumber('1.562641'); _sage_const_0p7150543 = RealNumber('0.7150543'); _sage_const_1p309847 = RealNumber('1.309847'); _sage_const_0p06640649 = RealNumber('0.06640649'); _sage_const_1p567667 = RealNumber('1.567667'); _sage_const_0p6961340 = RealNumber('0.6961340'); _sage_const_1p314886 = RealNumber('1.314886'); _sage_const_0p03157371 = RealNumber('0.03157371'); _sage_const_1p460012 = RealNumber('1.460012'); _sage_const_0p01554098 = RealNumber('0.01554098'); _sage_const_1p567632 = RealNumber('1.567632'); _sage_const_0p007746955 = RealNumber('0.007746955'); _sage_const_1p645371 = RealNumber('1.645371'); _sage_const_0p003881447 = RealNumber('0.003881447'); _sage_const_1p699469 = RealNumber('1.699469'); _sage_const_0p001948252 = RealNumber('0.001948252'); _sage_const_1p735811 = RealNumber('1.735811'); _sage_const_9p783026en4 = RealNumber('9.783026e-4'); _sage_const_1p759479 = RealNumber('1.759479'); _sage_const_4p911646en4 = RealNumber('4.911646e-4'); _sage_const_1p774490 = RealNumber('1.774490')
N = _sage_const_1000 
R = ComplexBallField(_sage_const_200 )
RF = RealField(_sage_const_200 )


# ---------------------------------------------------------------------------------------------
# Shared machinery -- verbatim from `verify_littlewoodshort_table.sage`:
# `JensenScaleConstants.lean`'s `sigma`/`vCoeff`/`mCoeff`/`bCoeff` and `c1,c2,c3`, plus
# `JensenBounds.lean`'s `c4` -- but with the `k = 0` triple of `JensenScaleConstantsAlt.lean`
# (`vCoeffAlt`, `vCoeffPAlt`, `vCoeffPPAlt`), which is what the paper's tables use.
# ---------------------------------------------------------------------------------------------


def sigma(k):
    if k == infinity:
        return _sage_const_1 
    elif k == -infinity:
        return _sage_const_0 
    elif k == _sage_const_0 :
        return QQ(_sage_const_1 ) / _sage_const_2 
    elif k > _sage_const_0 :
        return _sage_const_1  - (k + _sage_const_3 ) / (_sage_const_2  ** (k + _sage_const_3 ) - _sage_const_2 )
    else:
        return (-k + _sage_const_3 ) / (_sage_const_2  ** (-k + _sage_const_3 ) - _sage_const_2 )


def find_k(sig, Nn=N):
    upper, lower = Nn, -Nn
    vupper, vlower = sigma(upper), sigma(lower)
    if sig > vupper:
        return infinity
    if sig < vlower:
        return -infinity
    while upper - lower > _sage_const_1 :
        mid = (upper + lower) // _sage_const_2 
        vmid = sigma(mid)
        if sig < vmid:
            upper, vupper = mid, vmid
        elif sig > vmid:
            lower, vlower = mid, vmid
        else:
            return mid
    return lower


def vCoeff(k):
    if k == infinity:
        return _sage_const_0 
    elif k == -infinity:
        return QQ(_sage_const_1 ) / _sage_const_2 
    elif k == _sage_const_0 :
        return QQ(_sage_const_27 ) / _sage_const_164 
    elif k > _sage_const_0 :
        return _sage_const_1  / (_sage_const_2  ** (k + _sage_const_3 ) - _sage_const_2 )
    else:
        return QQ(_sage_const_1 ) / _sage_const_2  - sigma(k) + _sage_const_1  / (_sage_const_2  ** (-k + _sage_const_3 ) - _sage_const_2 )


def vCoeffP(k):
    return _sage_const_0  if k == _sage_const_0  else _sage_const_1 


def vCoeffPP(k, field=R):
    if k == _sage_const_0 :
        return log(field(_sage_const_667 ) / _sage_const_10 )
    elif k > _sage_const_0 :
        return log(field(_sage_const_1546 ) / _sage_const_1000 )
    else:
        return log(field(_sage_const_1546 ) / _sage_const_1000 ) + (sigma(k) - QQ(_sage_const_1 ) / _sage_const_2 ) * log(field(pi))


# CONVENTION (do not change without changing every evaluation site below):
# matches `eq:mk`/`eq:mkp`/`eq:mkpp` in the tex and `JensenScaleConstants.lean`'s
# `mCoeff`/`bCoeff` EXACTLY -- note the NEGATIVE denominator `sigma(k) - sigma(k+1)`.
# The chord is `mCoeff(k)*sigma + bCoeff(k)`, evaluated at `sigma` itself (NOT at `1-sigma`);
# it interpolates `(sigma_k, v_k) -> (sigma_{k+1}, v_{k+1})`.
def mCoeff(k):
    if k in (infinity, -infinity):
        return _sage_const_0 
    return (vCoeff(k) - vCoeff(k + _sage_const_1 )) / (sigma(k) - sigma(k + _sage_const_1 ))


def mCoeffP(k):
    if k in (infinity, -infinity):
        return _sage_const_0 
    return (vCoeffP(k) - vCoeffP(k + _sage_const_1 )) / (sigma(k) - sigma(k + _sage_const_1 ))


def mCoeffPP(k, field=R):
    if k in (infinity, -infinity):
        return _sage_const_0 
    return (vCoeffPP(k, field) - vCoeffPP(k + _sage_const_1 , field)) / (sigma(k) - sigma(k + _sage_const_1 ))


def bCoeff(k):
    return vCoeff(k) - mCoeff(k) * sigma(k)


def bCoeffP(k):
    return vCoeffP(k) - mCoeffP(k) * sigma(k)


def bCoeffPP(k, field=R):
    return vCoeffPP(k, field) - mCoeffPP(k, field) * sigma(k)


def coef(r, field=R, kcap=N):
    r"""`[c1(r), c2(r), c3(r)]`, certified when `field = R = ComplexBallField(200)` and
    `kcap = N = 1000`. `kcap` caps how many terms *past the starting `k`* are summed -- the sum is
    geometrically rapidly convergent (tex, after \eqref{eq:thetak}), so a small `kcap` (used only by
    `c1_fast` below, for the search) is a fast, non-certified approximation; the default `kcap = N`
    matches the original, fully-summed, certified computation.

    `r = 1` is a genuine edge case: `1 - r = 0` is below `sigma(k)` for *every* finite `k` (`sigma`
    only reaches `0` in the `k -> -infinity` limit), so `find_k(0) = -infinity` and the natural
    starting point for the sum is off the bottom of our `[-N, N]` discretization entirely -- the
    correct range to sum is then the *whole* `[-N, N]`, not `[-N, -N + kcap]` (which is what the
    general-case fallback below would give, since `k + kcap = -N + N = 0` when `k` gets clamped to
    `-N`)."""
    fk = find_k(_sage_const_1  - r)
    if fk == -infinity:
        k = -N
        kstop = N
    else:
        k = fk + _sage_const_1 
        if k < -N:
            k = -N
        kstop = min(N, k + kcap)
    C1 = C2 = C3 = field(_sage_const_0 )
    thetak = field(pi / _sage_const_2 )
    thetakp1 = (arcsin(field((_sage_const_1  - sigma(k)) / r))).real()
    while k < kstop:
        # `(m_k + b_k)*dtheta + m_k*r*dcos` -- exactly the sum printed in the tex after
        # \eqref{eq:thetak}, in the tex/Lean chord convention fixed above.
        cosdiff = cos(thetak) - cos(thetakp1)
        thetadiff = thetak - thetakp1
        C1 += r * cosdiff * mCoeff(k - _sage_const_1 ) + thetadiff * (mCoeff(k - _sage_const_1 ) + bCoeff(k - _sage_const_1 ))
        C2 += r * cosdiff * mCoeffP(k - _sage_const_1 ) + thetadiff * (mCoeffP(k - _sage_const_1 ) + bCoeffP(k - _sage_const_1 ))
        C3 += (r * cosdiff * mCoeffPP(k - _sage_const_1 , field)
               + thetadiff * (mCoeffPP(k - _sage_const_1 , field) + bCoeffPP(k - _sage_const_1 , field)))
        thetak = thetakp1
        k += _sage_const_1 
        thetakp1 = arcsin(field((_sage_const_1  - sigma(k)) / r)).real()
    return [field(C1), field(C2), field(C3)]


RD = RealField(_sage_const_53 )  # double precision, for the fast search only


def c1_fast(r):
    r"""`c1(r)` alone, in fast double-precision, 80-term-capped arithmetic -- for use inside the
    golden-section search only, where speed matters more than a certified error radius (the search
    only needs the *location* of the minimum; the final answer is re-evaluated certified, capped at
    the full `N = 1000`, once, after the search converges)."""
    return coef(RD(r), field=RD, kcap=_sage_const_80 )[_sage_const_0 ]


def integrable_logderzetaarcsin(rr, u, analytic):
    if analytic and u.real() > _sage_const_1  and u.imag().contains_zero():
        return CBF(NaN)
    return -rr * zetaderiv(_sage_const_1 , _sage_const_1  + rr * u) / zeta(_sage_const_1  + rr * u) * arcsin(u)


def c4r(r):
    val1 = R(log(zeta(_sage_const_1  + r)) / _sage_const_2 )
    val2 = (
        R.integral(lambda z, a: integrable_logderzetaarcsin(r, z, a), _sage_const_1  / _sage_const_2  ** _sage_const_100 , _sage_const_1 )
        + _sage_const_1  / _sage_const_2  ** _sage_const_99 
    ).real() / R(pi)
    return val1 + val2


# ---------------------------------------------------------------------------------------------
# `c5(r)` -- Proposition \ref{prop:outside3} (Proposition 23): `c5(r) = Phi(1+r)
# + (2r/pi) int_0^1 log(zeta(1+ru)) arcsin(u) du`.
# New (not in `verify_littlewoodshort_table.sage`), matching the notebook's `c5r`
# (`Phi(1+r) - 2*integral(-log(zeta(1+ru))... )`, same quantity, sign folded into the integrand
# there) and `RectangularBounds.lean`'s `c5`.
# ---------------------------------------------------------------------------------------------


def prime_power_heap_iterator(limit):
    from heapq import heappush, heappop, heapify

    pq = []
    max_k = ceil(log(limit) / log(_sage_const_2 ))
    for k in range(_sage_const_1 , max_k + _sage_const_1 ):
        it = (p ** k for p in primes(ceil(limit ** (_sage_const_1  / k))) if p ** k <= limit)
        try:
            first_val = next(it)
            pq.append((first_val, it, k))
        except StopIteration:
            break
    heapify(pq)
    while pq:
        val, it, k = heappop(pq)
        yield val
        try:
            nxt = next(it)
            heappush(pq, (nxt, it, k))
        except StopIteration:
            pass


def Phi_approx(X, z):
    sumval = _sage_const_0 
    r = z - _sage_const_1 
    for n in prime_power_heap_iterator(X):
        pp = is_prime_power(n, get_data=True)
        if pp[_sage_const_1 ] > _sage_const_0 :
            sumval += R(_sage_const_1  / pp[_sage_const_1 ] / log(n) / n ** (_sage_const_1  + r))
    if X >= _sage_const_10  ** _sage_const_10 :
        epsilon = _sage_const_64  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_9 :
        epsilon = _sage_const_198  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_8 :
        epsilon = _sage_const_738  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_7 :
        epsilon = _sage_const_2231  * _sage_const_10  ** (-_sage_const_7 )
    elif X >= _sage_const_10  ** _sage_const_6 :
        epsilon = _sage_const_6932  * _sage_const_10  ** (-_sage_const_7 )
    else:
        X = _sage_const_10  ** _sage_const_4 
        epsilon = _sage_const_8759  * _sage_const_10  ** (-_sage_const_6 )
    if r == _sage_const_0 :
        tail = R((_sage_const_1  / log(X) + _sage_const_1  / log(X) ** _sage_const_2 ) * (_sage_const_1  + epsilon))
    else:
        tail = R(
            (r ** _sage_const_2  * gamma_inc(-_sage_const_2 , R(r) * R(log(X))) + r * gamma_inc(-_sage_const_1 , R(r) * R(log(X))))
            * (r + _sage_const_1 )
            * (_sage_const_1  + epsilon)
        )
    return (sumval + tail).real()


def integrable_logzeta(z, analytic):
    if analytic and z.real() < _sage_const_0  and z.imag().contains_zero():
        return CBF(NaN)
    return log(zeta(z))


def Phi(z):
    if z == _sage_const_1 :
        val1 = R.integral(integrable_logzeta, z + _sage_const_1  / _sage_const_2  ** _sage_const_100 , _sage_const_1000 )
        val2 = R(-(_sage_const_1  / _sage_const_2  ** _sage_const_100 ) * (log(_sage_const_1  / _sage_const_2  ** _sage_const_100 ) - _sage_const_1 ))
    else:
        val1 = R.integral(integrable_logzeta, z, _sage_const_1000 )
        val2 = _sage_const_0 
    val3 = Phi_approx(_sage_const_10  ** _sage_const_6 , _sage_const_1000 )
    return val1 + val2 + val3


def integrable_logzeta_arcsin(r, u, analytic):
    if analytic and u.real() > _sage_const_1  and u.imag().contains_zero():
        return CBF(NaN)
    return log(zeta(_sage_const_1  + r * u)) * arcsin(u)


def c5r(r):
    val1 = Phi(_sage_const_1  + r).real()
    val2 = (
        _sage_const_2 
        * r
        * (R.integral(lambda z, a: integrable_logzeta_arcsin(r, z, a), _sage_const_1  / _sage_const_2  ** _sage_const_100 , _sage_const_1 )).real()
        / R(pi)
    )
    return val1 + val2


# ---------------------------------------------------------------------------------------------
# `C1,C2,C3` -- `Jensen/JensenBounds.lean`, Theorem \ref{thm:circularregions1} (Theorem 16);
# `B1,B2,B3,B4,rectDenom` -- `Jensen/RectangularBounds.lean`, Theorem
# \ref{thm:rectangularjensen} (Theorem 24).
# ---------------------------------------------------------------------------------------------


def C1_of(alpha, r, c1):
    return c1 / log(RF(r) / RF(alpha))


def C2_of(alpha, r, c2):
    lr = log(RF(r) / RF(alpha))
    return c2 / (lr * RF(pi)) + _sage_const_1  / lr


def C3_of(alpha, r, c3, c4):
    lr = log(RF(r) / RF(alpha))
    return c3 / (RF(pi) * lr) + c4 / lr + log(RF(_sage_const_29388 ) / _sage_const_1000 ) / lr


def rectDenom(r, alpha):
    r, alpha = RF(r), RF(alpha)
    return _sage_const_2  * r * sqrt(_sage_const_1  - (alpha / r) ** _sage_const_2 ) - _sage_const_2  * alpha * arctan(sqrt((r / alpha) ** _sage_const_2  - _sage_const_1 ))


# `Phi(1) = int_1^oo log|zeta(x)| dx < 1.7975699586287395`, the bound stated in Proposition
# \ref{prop:outside2} (Proposition 22). In Lean this is the hypothesis field
# `NumericCertificates.integral_log_zeta_Ioi_one_lt`, certified by `Code/verify_Phi_one_bound.sage`
# -- not by this script, which only consumes the value.
PHI1 = RF(_sage_const_1p7975699586287395 )


def B1_of(r, alpha, c1):
    return c1 / rectDenom(r, alpha)


def B2_of(r, alpha, c2):
    return c2 / (RF(pi) * rectDenom(r, alpha))


def B3_of(r, alpha, c3):
    return c3 / (RF(pi) * rectDenom(r, alpha))


def B4_of(r, alpha, c5):
    # `B_{4,alpha,r} = (2*Phi(1) + c_{5,r})/D_{r,alpha}`, Theorem \ref{thm:rectangularjensen}
    # (Theorem 24). NOT `Phi(1)/pi`: Proposition \ref{prop:outside2} (Proposition 22) states its
    # bound in `(1/(2pi))`-normalised form `(1/(2pi)) int log|zeta(1+it)|dt <= Phi(1)/pi`, i.e.
    # `int log|zeta(1+it)|dt <= 2*Phi(1)`, and it is the *un-normalised* integral that occurs bare
    # in the numerator of Proposition \ref{prop:jensenrectangle} (Proposition 19).
    # Matches `RectangularBounds.lean`'s `B4` exactly (see its docstring for the full argument).
    return (_sage_const_2  * PHI1 + c5) / rectDenom(r, alpha)


# ---------------------------------------------------------------------------------------------
# Golden-section search for the `r in (alpha, 1)` minimizing `c1_fast(r)/weight(r,alpha)`.
# ---------------------------------------------------------------------------------------------

GOLDEN = (sqrt(RF(_sage_const_5 )) - _sage_const_1 ) / _sage_const_2   # 1/phi


def golden_section_min(f, lo, hi, iters=_sage_const_45 ):
    lo, hi = RF(lo), RF(hi)
    x1 = hi - GOLDEN * (hi - lo)
    x2 = lo + GOLDEN * (hi - lo)
    f1, f2 = f(x1), f(x2)
    for _ in range(iters):
        if f1 < f2:
            hi, x2, f2 = x2, x1, f1
            x1 = hi - GOLDEN * (hi - lo)
            f1 = f(x1)
        else:
            lo, x1, f1 = x1, x2, f2
            x2 = lo + GOLDEN * (hi - lo)
            f2 = f(x2)
    return (lo + hi) / _sage_const_2 


def optimal_r_Cvalues(alpha):
    weight = lambda r: log(RF(r) / RF(alpha))
    f = lambda r: c1_fast(r) / weight(r)
    return golden_section_min(f, RF(alpha) * RF(_sage_const_1p001 ), RF(_sage_const_0p999999 ))


def optimal_r_rectangular(alpha):
    f = lambda r: c1_fast(r) / rectDenom(r, alpha)
    return golden_section_min(f, RF(alpha) * RF(_sage_const_1p001 ), RF(_sage_const_0p999999 ))


def roundup_to(v, ndig):
    v = RF(v)
    if v == _sage_const_0 :
        return RF(_sage_const_0 )
    d = ceil(log(v) / log(_sage_const_10 ))
    if d < _sage_const_1 :
        scaled = ceil(v * _sage_const_10  ** (_sage_const_1  + _sage_const_7  - d)) / _sage_const_10  ** (_sage_const_1  + _sage_const_7  - d)
    else:
        scaled = ceil(v * _sage_const_10  ** _sage_const_7 ) / _sage_const_10  ** _sage_const_7 
    return RF(scaled)


def compare(name, computed, want, worst_ref):
    computed = RF(computed)
    rounded = roundup_to(computed, _sage_const_7 )
    gap = abs(RF(want) - rounded) / max(abs(RF(want)), RF(_sage_const_1en30 ))
    worst_ref[_sage_const_0 ] = max(worst_ref[_sage_const_0 ], gap)
    flag = "" if gap < _sage_const_1en4  else "   <-- MISMATCH"
    print(f"    {name:8s} computed={computed:.10g}  roundup7={rounded:.10g}"
          f"  tex={want:.10g}{flag}")


# =================================================================================================
# tab:crvalues -- Table 2 of the tex -- [r, c1, c2, c3, c4, c5]
# =================================================================================================

TABLE1_R = [_sage_const_1 , QQ(_sage_const_1 )/_sage_const_2 , QQ(_sage_const_1 )/_sage_const_3 , QQ(_sage_const_1 )/_sage_const_4 , QQ(_sage_const_1 )/_sage_const_5 , QQ(_sage_const_1 )/_sage_const_6 , QQ(_sage_const_1 )/_sage_const_7 , QQ(_sage_const_1 )/_sage_const_8 , QQ(_sage_const_1 )/_sage_const_9 , QQ(_sage_const_1 )/_sage_const_10 ,
            QQ(_sage_const_1 )/_sage_const_11 , QQ(_sage_const_1 )/_sage_const_12 , QQ(_sage_const_1 )/_sage_const_13 , QQ(_sage_const_1 )/_sage_const_14 , QQ(_sage_const_1 )/_sage_const_15 , QQ(_sage_const_1 )/_sage_const_16 , QQ(_sage_const_1 )/_sage_const_32 , QQ(_sage_const_1 )/_sage_const_64 ,
            QQ(_sage_const_1 )/_sage_const_128 , QQ(_sage_const_1 )/_sage_const_256 , QQ(_sage_const_1 )/_sage_const_512 , QQ(_sage_const_1 )/_sage_const_1024 , QQ(_sage_const_1 )/_sage_const_2048 ]

TEX_TABLE1 = {
    _sage_const_1 : [_sage_const_0p4260491 , _sage_const_1p320694 , _sage_const_1p233886 , _sage_const_0p5099522 , _sage_const_0p8331601 ],
    QQ(_sage_const_1 )/_sage_const_2 : [_sage_const_0p1467868 , _sage_const_0p9393432 , _sage_const_3p061478 , _sage_const_0p7795712 , _sage_const_1p126439 ],
    QQ(_sage_const_1 )/_sage_const_3 : [_sage_const_0p08122972 , _sage_const_1p491029 , _sage_const_0p9846382 , _sage_const_0p9546469 , _sage_const_1p271554 ],
    QQ(_sage_const_1 )/_sage_const_4 : [_sage_const_0p05402652 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p084244 , _sage_const_1p360125 ],
    QQ(_sage_const_1 )/_sage_const_5 : [_sage_const_0p03956564 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p187130 , _sage_const_1p420588 ],
    QQ(_sage_const_1 )/_sage_const_6 : [_sage_const_0p03071227 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p272441 , _sage_const_1p464849 ],
    QQ(_sage_const_1 )/_sage_const_7 : [_sage_const_0p02516876 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p345309 , _sage_const_1p498839 ],
    QQ(_sage_const_1 )/_sage_const_8 : [_sage_const_0p02110448 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p408902 , _sage_const_1p525868 ],
    QQ(_sage_const_1 )/_sage_const_9 : [_sage_const_0p01803813 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p465317 , _sage_const_1p547944 ],
    QQ(_sage_const_1 )/_sage_const_10 : [_sage_const_0p01569390 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p516009 , _sage_const_1p566357 ],
    QQ(_sage_const_1 )/_sage_const_11 : [_sage_const_0p01393216 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p562034 , _sage_const_1p581977 ],
    QQ(_sage_const_1 )/_sage_const_12 : [_sage_const_0p01249892 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p604178 , _sage_const_1p595417 ],
    QQ(_sage_const_1 )/_sage_const_13 : [_sage_const_0p01129907 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p643045 , _sage_const_1p607118 ],
    QQ(_sage_const_1 )/_sage_const_14 : [_sage_const_0p01028337 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p679108 , _sage_const_1p617407 ],
    QQ(_sage_const_1 )/_sage_const_15 : [_sage_const_0p009416022 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p712745 , _sage_const_1p626535 ],
    QQ(_sage_const_1 )/_sage_const_16 : [_sage_const_0p008670644 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p744261 , _sage_const_1p634694 ],
    QQ(_sage_const_1 )/_sage_const_32 : [_sage_const_0p003703026 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_2p085161 , _sage_const_1p702482 ],
    QQ(_sage_const_1 )/_sage_const_64 : [_sage_const_0p001626574 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_2p428881 , _sage_const_1p743167 ],
    QQ(_sage_const_1 )/_sage_const_128 : [_sage_const_7p256286en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_2p774023 , _sage_const_1p766930 ],
    QQ(_sage_const_1 )/_sage_const_256 : [_sage_const_3p277390en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_3p119880 , _sage_const_1p780529 ],
    QQ(_sage_const_1 )/_sage_const_512 : [_sage_const_1p495313en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_3p466095 , _sage_const_1p788188 ],
    QQ(_sage_const_1 )/_sage_const_1024 : [_sage_const_6p880172en5 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_3p812489 , _sage_const_1p792449 ],
    QQ(_sage_const_1 )/_sage_const_2048 : [_sage_const_3p188568en5 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_4p158973 , _sage_const_1p794794 ],
}

print("\n=== Table 1 (tab:crvalues): c1,c2,c3,c4,c5 ===\n")
worst1 = [_sage_const_0 ]
for r in TABLE1_R:
    c1, c2, c3 = coef(r)
    c4 = c4r(r)
    c5 = c5r(r)
    print(f"r = {r} :")
    for nm, comp, want in zip(["c1", "c2", "c3", "c4", "c5"], [c1, c2, c3, c4, c5],
                               TEX_TABLE1[r]):
        compare(nm, comp, want, worst1)
    print()
print(f"Table 1 worst relative gap: {worst1[_sage_const_0 ]:.3e}")


# =================================================================================================
# tab:CRvalues -- Table 3 of the tex -- [alpha, r, C1, C2, C3, r/alpha]
# (optimal r minimizing C1(alpha,r) = c1(r)/log(r/alpha))
# =================================================================================================

TABLE24_ALPHA = [QQ(_sage_const_1 )/_sage_const_3 , QQ(_sage_const_1 )/_sage_const_4 , QQ(_sage_const_1 )/_sage_const_5 , QQ(_sage_const_1 )/_sage_const_6 , QQ(_sage_const_1 )/_sage_const_7 , QQ(_sage_const_1 )/_sage_const_8 , QQ(_sage_const_1 )/_sage_const_9 , QQ(_sage_const_1 )/_sage_const_10 ,
                 QQ(_sage_const_1 )/_sage_const_11 , QQ(_sage_const_1 )/_sage_const_12 , QQ(_sage_const_1 )/_sage_const_13 , QQ(_sage_const_1 )/_sage_const_14 , QQ(_sage_const_1 )/_sage_const_15 , QQ(_sage_const_1 )/_sage_const_16 , QQ(_sage_const_1 )/_sage_const_32 , QQ(_sage_const_1 )/_sage_const_64 ,
                 QQ(_sage_const_1 )/_sage_const_128 , QQ(_sage_const_1 )/_sage_const_256 , QQ(_sage_const_1 )/_sage_const_512 , QQ(_sage_const_1 )/_sage_const_1024 , QQ(_sage_const_1 )/_sage_const_2048 ]

TEX_TABLE2 = {
    QQ(_sage_const_1 )/_sage_const_3 : [_sage_const_0p6490511 , _sage_const_0p3264740 , _sage_const_1p965836 , _sage_const_7p446222 , _sage_const_1p947154 ],
    QQ(_sage_const_1 )/_sage_const_4 : [_sage_const_0p5022756 , _sage_const_0p2117515 , _sage_const_1p858502 , _sage_const_7p369401 , _sage_const_2p009103 ],
    QQ(_sage_const_1 )/_sage_const_5 : [_sage_const_0p3940064 , _sage_const_0p1538013 , _sage_const_2p093277 , _sage_const_7p054466 , _sage_const_1p970032 ],
    QQ(_sage_const_1 )/_sage_const_6 : [_sage_const_0p3242696 , _sage_const_0p1170874 , _sage_const_2p225533 , _sage_const_6p965111 , _sage_const_1p945618 ],
    QQ(_sage_const_1 )/_sage_const_7 : [_sage_const_0p2897366 , _sage_const_0p09333569 , _sage_const_2p120321 , _sage_const_6p530988 , _sage_const_2p028157 ],
    QQ(_sage_const_1 )/_sage_const_8 : [_sage_const_0p2606756 , _sage_const_0p07783097 , _sage_const_2p040920 , _sage_const_6p345352 , _sage_const_2p085405 ],
    QQ(_sage_const_1 )/_sage_const_9 : [_sage_const_0p2276378 , _sage_const_0p06616898 , _sage_const_2p091395 , _sage_const_6p588795 , _sage_const_2p048740 ],
    QQ(_sage_const_1 )/_sage_const_10 : [_sage_const_0p2030836 , _sage_const_0p05706802 , _sage_const_2p117307 , _sage_const_6p744948 , _sage_const_2p030836 ],
    QQ(_sage_const_1 )/_sage_const_11 : [_sage_const_0p1851792 , _sage_const_0p04988792 , _sage_const_2p108330 , _sage_const_6p776810 , _sage_const_2p036971 ],
    QQ(_sage_const_1 )/_sage_const_12 : [_sage_const_0p1729682 , _sage_const_0p04420265 , _sage_const_2p054067 , _sage_const_6p646159 , _sage_const_2p075618 ],
    QQ(_sage_const_1 )/_sage_const_13 : [_sage_const_0p1668192 , _sage_const_0p03972128 , _sage_const_1p937723 , _sage_const_6p291698 , _sage_const_2p168650 ],
    QQ(_sage_const_1 )/_sage_const_14 : [_sage_const_0p1550286 , _sage_const_0p03611895 , _sage_const_1p935706 , _sage_const_6p329759 , _sage_const_2p170400 ],
    QQ(_sage_const_1 )/_sage_const_15 : [_sage_const_0p1433184 , _sage_const_0p03302353 , _sage_const_1p959855 , _sage_const_6p457329 , _sage_const_2p149775 ],
    QQ(_sage_const_1 )/_sage_const_16 : [_sage_const_0p1333413 , _sage_const_0p03033976 , _sage_const_1p979559 , _sage_const_6p567526 , _sage_const_2p133460 ],
    QQ(_sage_const_1 )/_sage_const_32 : [_sage_const_0p06834560 , _sage_const_0p01242107 , _sage_const_1p916792 , _sage_const_6p771429 , _sage_const_2p187059 ],
    QQ(_sage_const_1 )/_sage_const_64 : [_sage_const_0p03512879 , _sage_const_0p005269206 , _sage_const_1p851512 , _sage_const_6p944143 , _sage_const_2p248243 ],
    QQ(_sage_const_1 )/_sage_const_128 : [_sage_const_0p01817011 , _sage_const_0p002295522 , _sage_const_1p777141 , _sage_const_7p052067 , _sage_const_2p325774 ],
    QQ(_sage_const_1 )/_sage_const_256 : [_sage_const_0p009413507 , _sage_const_0p001021403 , _sage_const_1p705384 , _sage_const_7p139335 , _sage_const_2p409858 ],
    QQ(_sage_const_1 )/_sage_const_512 : [_sage_const_0p004727625 , _sage_const_4p607252en4 , _sage_const_1p696848 , _sage_const_7p492183 , _sage_const_2p420544 ],
    QQ(_sage_const_1 )/_sage_const_1024 : [_sage_const_0p002374581 , _sage_const_2p099090en4 , _sage_const_1p688169 , _sage_const_7p840865 , _sage_const_2p431570 ],
    QQ(_sage_const_1 )/_sage_const_2048 : [_sage_const_0p001192880 , _sage_const_9p643198en5 , _sage_const_1p679292 , _sage_const_8p184763 , _sage_const_2p443018 ],
}

print("\n=== Table 2 (tab:CRvalues): r*, C1, C2, C3, r*/alpha ===\n")
worst2 = [_sage_const_0 ]
table2_r = {}
for alpha in TABLE24_ALPHA:
    rstar = optimal_r_Cvalues(alpha)
    table2_r[alpha] = rstar
    c1, c2, c3 = coef(QQ(RealField(_sage_const_120 )(rstar)))
    c4 = c4r(QQ(RealField(_sage_const_120 )(rstar)))
    C1v = C1_of(alpha, rstar, RF(c1))
    C2v = C2_of(alpha, rstar, RF(c2))
    C3v = C3_of(alpha, rstar, RF(c3), RF(c4))
    print(f"alpha = 1/{QQ(_sage_const_1 )/alpha} :")
    for nm, comp, want in zip(["r", "C1", "C2", "C3", "r/alpha"],
                               [rstar, C1v, C2v, C3v, rstar / alpha], TEX_TABLE2[alpha]):
        compare(nm, comp, want, worst2)
    print()
print(f"Table 2 worst relative gap: {worst2[_sage_const_0 ]:.3e}")


# =================================================================================================
# tab:crvalues2 -- Table 4 of the tex -- [r, c1, c2, c3, c4] at tab:CRvalues's r values
# =================================================================================================

print("\n=== Table 3 (tab:crvalues2): c1,c2,c3,c4 at Table 2's r ===\n")
worst3 = [_sage_const_0 ]
TEX_TABLE3 = list(zip(
    [_sage_const_0p6490511 , _sage_const_0p5022756 , _sage_const_0p3940064 , _sage_const_0p3242696 , _sage_const_0p2897366 , _sage_const_0p2606756 , _sage_const_0p2276378 , _sage_const_0p2030836 ,
     _sage_const_0p1851792 , _sage_const_0p1729682 , _sage_const_0p1668192 , _sage_const_0p1550286 , _sage_const_0p1433183 , _sage_const_0p1333413 , _sage_const_0p06834559 , _sage_const_0p03512879 ,
     _sage_const_0p01817011 , _sage_const_0p009413510 , _sage_const_0p004727620 , _sage_const_0p002374580 , _sage_const_0p001192880 ],
    [[_sage_const_0p2175520 , _sage_const_0p9738017 , _sage_const_2p853749 , _sage_const_0p6729643 ],
     [_sage_const_0p1477365 , _sage_const_0p9319669 , _sage_const_3p089081 , _sage_const_0p7776710 ],
     [_sage_const_0p1042849 , _sage_const_1p317413 , _sage_const_1p638224 , _sage_const_0p8812288 ],
     [_sage_const_0p07793089 , _sage_const_1p511949 , _sage_const_0p9058834 , _sage_const_0p9668954 ],
     [_sage_const_0p06600019 , _sage_const_1p568710 , _sage_const_0p6922055 , _sage_const_1p017316 ],
     [_sage_const_0p05720288 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p065177 ],
     [_sage_const_0p04745803 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p127225 ],
     [_sage_const_0p04042969 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p180019 ],
     [_sage_const_0p03549344 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p223032 ],
     [_sage_const_0p03227938 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p254995 ],
     [_sage_const_0p03074843 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p272011 ],
     [_sage_const_0p02798899 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p306581 ],
     [_sage_const_0p02527499 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p343779 ],
     [_sage_const_0p02298980 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p378087 ],
     [_sage_const_0p009720201 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p700612 ],
     [_sage_const_0p004268841 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_2p027367 ],
     [_sage_const_0p001937541 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_2p353894 ],
     [_sage_const_8p983930en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_2p681106 ],
     [_sage_const_4p072770en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_3p024609 ],
     [_sage_const_1p865119en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_3p368478 ],
     [_sage_const_8p613635en5 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_3p712486 ]],
))
for alpha, (r_tex, row) in zip(TABLE24_ALPHA, TEX_TABLE3):
    rstar = table2_r[alpha]
    c1, c2, c3 = coef(QQ(RealField(_sage_const_120 )(rstar)))
    c4 = c4r(QQ(RealField(_sage_const_120 )(rstar)))
    print(f"alpha = 1/{QQ(_sage_const_1 )/alpha}  (tex r={r_tex}, ours r={RF(rstar):.7g}) :")
    for nm, comp, want in zip(["c1", "c2", "c3", "c4"], [c1, c2, c3, c4], row):
        compare(nm, comp, want, worst3)
    print()
print(f"Table 3 worst relative gap: {worst3[_sage_const_0 ]:.3e}")


# =================================================================================================
# tab:rectangularjensen -- Table 5 of the tex -- [alpha, r, B1, B2, B3, B4, hat_alpha_r, r/alpha]
# (optimal r minimizing B1(alpha,r) = c1(r)/rectDenom(r,alpha))
# =================================================================================================

TABLE4_ALPHA = [QQ(_sage_const_1 )/_sage_const_7 , QQ(_sage_const_1 )/_sage_const_8 , QQ(_sage_const_1 )/_sage_const_9 , QQ(_sage_const_1 )/_sage_const_10 , QQ(_sage_const_1 )/_sage_const_11 , QQ(_sage_const_1 )/_sage_const_12 , QQ(_sage_const_1 )/_sage_const_13 , QQ(_sage_const_1 )/_sage_const_14 ,
                QQ(_sage_const_1 )/_sage_const_15 , QQ(_sage_const_1 )/_sage_const_16 , QQ(_sage_const_1 )/_sage_const_32 , QQ(_sage_const_1 )/_sage_const_64 , QQ(_sage_const_1 )/_sage_const_128 , QQ(_sage_const_1 )/_sage_const_256 , QQ(_sage_const_1 )/_sage_const_512 ,
                QQ(_sage_const_1 )/_sage_const_1024 , QQ(_sage_const_1 )/_sage_const_2048 ]

TEX_TABLE4 = {
    QQ(_sage_const_1 )/_sage_const_7 : [_sage_const_0p5647100 , _sage_const_0p2457053 , _sage_const_0p3900919 , _sage_const_1p450119 , _sage_const_6p518765 , _sage_const_0p5463417 , _sage_const_3p952970 ],
    QQ(_sage_const_1 )/_sage_const_8 : [_sage_const_0p5185446 , _sage_const_0p2294753 , _sage_const_0p4239720 , _sage_const_1p514935 , _sage_const_6p977388 , _sage_const_0p5032529 , _sage_const_4p148357 ],
    QQ(_sage_const_1 )/_sage_const_9 : [_sage_const_0p5030821 , _sage_const_0p2172051 , _sage_const_0p4340594 , _sage_const_1p446353 , _sage_const_6p922300 , _sage_const_0p4906586 , _sage_const_4p527739 ],
    QQ(_sage_const_1 )/_sage_const_10 : [_sage_const_0p4821212 , _sage_const_0p2079206 , _sage_const_0p4778655 , _sage_const_1p331336 , _sage_const_7p058488 , _sage_const_0p4716364 , _sage_const_4p821212 ],
    QQ(_sage_const_1 )/_sage_const_11 : [_sage_const_0p3820330 , _sage_const_0p1991813 , _sage_const_0p8624038 , _sage_const_0p9519504 , _sage_const_9p637060 , _sage_const_0p3710589 , _sage_const_4p202362 ],
    QQ(_sage_const_1 )/_sage_const_12 : [_sage_const_0p3390065 , _sage_const_0p1907470 , _sage_const_1p076388 , _sage_const_0p7557944 , _sage_const_11p128858 , _sage_const_0p3286046 , _sage_const_4p068078 ],
    QQ(_sage_const_1 )/_sage_const_13 : [_sage_const_0p3165097 , _sage_const_0p1832274 , _sage_const_1p186113 , _sage_const_0p6552031 , _sage_const_11p906782 , _sage_const_0p3070199 , _sage_const_4p114626 ],
    QQ(_sage_const_1 )/_sage_const_14 : [_sage_const_0p3035626 , _sage_const_0p1767236 , _sage_const_1p236003 , _sage_const_0p6023857 , _sage_const_12p253958 , _sage_const_0p2950393 , _sage_const_4p249876 ],
    QQ(_sage_const_1 )/_sage_const_15 : [_sage_const_0p2957571 , _sage_const_0p1711536 , _sage_const_1p252382 , _sage_const_0p5730817 , _sage_const_12p349950 , _sage_const_0p2881455 , _sage_const_4p436356 ],
    QQ(_sage_const_1 )/_sage_const_16 : [_sage_const_0p2909922 , _sage_const_0p1663861 , _sage_const_1p250289 , _sage_const_0p5551999 , _sage_const_12p302409 , _sage_const_0p2842010 , _sage_const_4p655874 ],
    QQ(_sage_const_1 )/_sage_const_32 : [_sage_const_0p1701799 , _sage_const_0p1273443 , _sage_const_2p016620 , _sage_const_0p8785824 , _sage_const_20p388630 , _sage_const_0p1672861 , _sage_const_5p445757 ],
    QQ(_sage_const_1 )/_sage_const_64 : [_sage_const_0p09924636 , _sage_const_0p1023306 , _sage_const_3p292282 , _sage_const_1p434352 , _sage_const_33p994587 , _sage_const_0p09800867 , _sage_const_6p351767 ],
    QQ(_sage_const_1 )/_sage_const_128 : [_sage_const_0p05717608 , _sage_const_0p08524602 , _sage_const_5p501905 , _sage_const_2p397021 , _sage_const_57p665580 , _sage_const_0p05663982 , _sage_const_7p318538 ],
    QQ(_sage_const_1 )/_sage_const_256 : [_sage_const_0p03250649 , _sage_const_0p07294429 , _sage_const_9p396536 , _sage_const_4p093798 , _sage_const_99p501950 , _sage_const_0p03227093 , _sage_const_8p321661 ],
    QQ(_sage_const_1 )/_sage_const_512 : [_sage_const_0p01825477 , _sage_const_0p06370419 , _sage_const_16p349070 , _sage_const_7p122815 , _sage_const_174p312148 , _sage_const_0p01814999 , _sage_const_9p346441 ],
    QQ(_sage_const_1 )/_sage_const_1024 : [_sage_const_0p01014060 , _sage_const_0p05652525 , _sage_const_28p889451 , _sage_const_12p586295 , _sage_const_309p383987 , _sage_const_0p01009347 , _sage_const_10p383974 ],
    QQ(_sage_const_1 )/_sage_const_2048 : [_sage_const_0p005580532 , _sage_const_0p05079351 , _sage_const_51p707199 , _sage_const_22p527325 , _sage_const_555p296995 , _sage_const_0p005559130 ,
                 _sage_const_11p428930 ],
}

# `B_{4,alpha,r}` per Theorem \ref{thm:rectangularjensen} (Theorem 24):
# `(2*Phi(1) + c_{5,r})/D_{r,alpha}`.
print("\n=== Table 4 (tab:rectangularjensen): r*, B1, B2, B3, B4, hat_alpha_r, r*/alpha ===\n")
worst4 = [_sage_const_0 ]
table4_r = {}
for alpha in TABLE4_ALPHA:
    rstar = optimal_r_rectangular(alpha)
    table4_r[alpha] = rstar
    c1, c2, c3 = coef(QQ(RealField(_sage_const_120 )(rstar)))
    c5 = c5r(QQ(RealField(_sage_const_120 )(rstar)))
    B1v = B1_of(rstar, alpha, RF(c1))
    B2v = B2_of(rstar, alpha, RF(c2))
    B3v = B3_of(rstar, alpha, RF(c3))
    B4v = B4_of(rstar, alpha, RF(c5))
    hat_alpha_r = sqrt(RF(rstar) ** _sage_const_2  - RF(alpha) ** _sage_const_2 )
    print(f"alpha = 1/{QQ(_sage_const_1 )/alpha} :")
    for nm, comp, want in zip(["r", "B1", "B2", "B3", "B4", "hat_alpha_r", "r/alpha"],
                               [rstar, B1v, B2v, B3v, B4v, hat_alpha_r, rstar / alpha],
                               TEX_TABLE4[alpha]):
        compare(nm, comp, want, worst4)
    print()
print(f"Table 4 worst relative gap: {worst4[_sage_const_0 ]:.3e}")


# =================================================================================================
# tab:crvalues3 -- Table 6 of the tex -- [r, c1, c2, c3, c5] at tab:rectangularjensen's r values
# =================================================================================================

print("\n=== Table 5 (tab:crvalues3): c1,c2,c3,c5 at Table 4's r ===\n")
worst5 = [_sage_const_0 ]
TEX_TABLE5 = list(zip(
    [_sage_const_0p5647100 , _sage_const_0p5185446 , _sage_const_0p5030821 , _sage_const_0p4821212 , _sage_const_0p3820329 , _sage_const_0p3390065 , _sage_const_0p3165097 , _sage_const_0p3035626 ,
     _sage_const_0p2957571 , _sage_const_0p2909922 , _sage_const_0p1701799 , _sage_const_0p09924635 , _sage_const_0p05717607 , _sage_const_0p03250649 , _sage_const_0p01825477 , _sage_const_0p01014060 ,
     _sage_const_0p005580530 ],
    [[_sage_const_0p1761601 , _sage_const_0p8786375 , _sage_const_3p266227 , _sage_const_1p078532 ],
     [_sage_const_0p1548203 , _sage_const_0p8986260 , _sage_const_3p210968 , _sage_const_1p112301 ],
     [_sage_const_0p1480773 , _sage_const_0p9296458 , _sage_const_3p097724 , _sage_const_1p124066 ],
     [_sage_const_0p1394940 , _sage_const_1p007195 , _sage_const_2p806049 , _sage_const_1p140402 ],
     [_sage_const_0p09963112 , _sage_const_1p355212 , _sage_const_1p495928 , _sage_const_1p225349 ],
     [_sage_const_0p08331889 , _sage_const_1p477082 , _sage_const_1p037145 , _sage_const_1p265982 ],
     [_sage_const_0p07515015 , _sage_const_1p528325 , _sage_const_0p8442389 , _sage_const_1p288392 ],
     [_sage_const_0p07062081 , _sage_const_1p551699 , _sage_const_0p7562453 , _sage_const_1p301685 ],
     [_sage_const_0p06797647 , _sage_const_1p562641 , _sage_const_0p7150543 , _sage_const_1p309847 ],
     [_sage_const_0p06640649 , _sage_const_1p567667 , _sage_const_0p6961340 , _sage_const_1p314886 ],
     [_sage_const_0p03157371 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p460012 ],
     [_sage_const_0p01554098 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p567632 ],
     [_sage_const_0p007746955 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p645371 ],
     [_sage_const_0p003881447 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p699469 ],
     [_sage_const_0p001948252 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p735811 ],
     [_sage_const_9p783026en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p759479 ],
     [_sage_const_4p911646en4 , _sage_const_1p570797 , _sage_const_0p6843504 , _sage_const_1p774490 ]],
))
for alpha, (r_tex, row) in zip(TABLE4_ALPHA, TEX_TABLE5):
    rstar = table4_r[alpha]
    c1, c2, c3 = coef(QQ(RealField(_sage_const_120 )(rstar)))
    c5 = c5r(QQ(RealField(_sage_const_120 )(rstar)))
    print(f"alpha = 1/{QQ(_sage_const_1 )/alpha}  (tex r={r_tex}, ours r={RF(rstar):.7g}) :")
    for nm, comp, want in zip(["c1", "c2", "c3", "c5"], [c1, c2, c3, c5], row):
        compare(nm, comp, want, worst5)
    print()
print(f"Table 5 worst relative gap: {worst5[_sage_const_0 ]:.3e}")

print("\n=== Overall worst relative gap across Tables 1-5: "
      f"{max(worst1[_sage_const_0 ], worst2[_sage_const_0 ], worst3[_sage_const_0 ], worst4[_sage_const_0 ], worst5[_sage_const_0 ]):.3e} ===")

